// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package mathml munder is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// This element is used to display an expression with an underbar.
type MathMLMUNDERElement struct {
	*Element
}

// Create a new MathMLMUNDERElement element.
// This will create a new element with the tag
// "munder" during rendering.
func MathML_MUNDER(children ...ElementRenderer) *MathMLMUNDERElement {
	e := NewElement("munder", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &MathMLMUNDERElement{Element: e}
}

func (e *MathMLMUNDERElement) Children(children ...ElementRenderer) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *MathMLMUNDERElement) IfChildren(condition bool, children ...ElementRenderer) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *MathMLMUNDERElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *MathMLMUNDERElement) BoolAttr(name string) *MathMLMUNDERElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *MathMLMUNDERElement) IfBoolAttr(condition bool, name string) *MathMLMUNDERElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *MathMLMUNDERElement) Attr(name, value string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *MathMLMUNDERElement) IfAttr(condition bool, name, value string) *MathMLMUNDERElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *MathMLMUNDERElement) Text(text string) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *MathMLMUNDERElement) TextF(format string, args ...any) *MathMLMUNDERElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfText(condition bool, text string) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *MathMLMUNDERElement) IfTextF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *MathMLMUNDERElement) Escaped(text string) *MathMLMUNDERElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *MathMLMUNDERElement) IfEscaped(condition bool, text string) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *MathMLMUNDERElement) EscapedF(format string, args ...any) *MathMLMUNDERElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfEscapedF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *MathMLMUNDERElement) CustomData(key, value string) *MathMLMUNDERElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *MathMLMUNDERElement) IfCustomData(condition bool, key, value string) *MathMLMUNDERElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *MathMLMUNDERElement) CustomDataF(key, format string, args ...any) *MathMLMUNDERElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *MathMLMUNDERElement) IfCustomDataF(condition bool, key, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *MathMLMUNDERElement) CustomDataRemove(key string) *MathMLMUNDERElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLMUNDERElement) CLASS(s string) *MathMLMUNDERElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLMUNDERElement) IfCLASS(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
//
// Remove the values from the attribute CLASS in the element.
func (e *MathMLMUNDERElement) CLASSRemove(s ...string) *MathMLMUNDERElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
func (e *MathMLMUNDERElement) DIR(c MathMLMunderDirChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dir", string(c))
	return e
}

type MathMLMunderDirChoice string

const (
	// left-to-right
	MathMLMunderDir_ltr MathMLMunderDirChoice = "ltr"
	// right-to-left
	MathMLMunderDir_rtl MathMLMunderDirChoice = "rtl"
)

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
// Remove the attribute DIR from the element.
func (e *MathMLMUNDERElement) DIRRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dir")
	return e
}

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
func (e *MathMLMUNDERElement) DISPLAYSTYLE(c MathMLMunderDisplaystyleChoice) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("displaystyle", string(c))
	return e
}

type MathMLMunderDisplaystyleChoice string

const (
	// displaystyle rules
	MathMLMunderDisplaystyle_true MathMLMunderDisplaystyleChoice = "true"
	// not displaystyle rules
	MathMLMunderDisplaystyle_false MathMLMunderDisplaystyleChoice = "false"
)

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
// Remove the attribute DISPLAYSTYLE from the element.
func (e *MathMLMUNDERElement) DISPLAYSTYLERemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("displaystyle")
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMUNDERElement) ID(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMUNDERElement) IDF(format string, args ...any) *MathMLMUNDERElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMUNDERElement) IfID(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.ID(s)
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMUNDERElement) IfIDF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
//
// Remove the attribute ID from the element.
func (e *MathMLMUNDERElement) IDRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHBACKGROUND(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathbackground", s)
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHBACKGROUNDF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHBACKGROUND(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHBACKGROUND(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHBACKGROUND(s)
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHBACKGROUNDF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHBACKGROUND(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
//
// Remove the attribute MATHBACKGROUND from the element.
func (e *MathMLMUNDERElement) MATHBACKGROUNDRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathbackground")
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHCOLOR(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathcolor", s)
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMUNDERElement) MATHCOLORF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHCOLOR(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHCOLOR(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHCOLOR(s)
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMUNDERElement) IfMATHCOLORF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHCOLOR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
//
// Remove the attribute MATHCOLOR from the element.
func (e *MathMLMUNDERElement) MATHCOLORRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathcolor")
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMUNDERElement) MATHSIZE_STR(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathsize", s)
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMUNDERElement) MATHSIZE_STRF(format string, args ...any) *MathMLMUNDERElement {
	return e.MATHSIZE_STR(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMUNDERElement) IfMATHSIZE_STR(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.MATHSIZE_STR(s)
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMUNDERElement) IfMATHSIZE_STRF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.MATHSIZE_STR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
//
// Remove the attribute MATHSIZE_STR from the element.
func (e *MathMLMUNDERElement) MATHSIZE_STRRemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathsize")
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) NONCE(s string) *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("nonce", s)
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) NONCEF(format string, args ...any) *MathMLMUNDERElement {
	return e.NONCE(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) IfNONCE(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.NONCE(s)
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMUNDERElement) IfNONCEF(condition bool, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.NONCE(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
//
// Remove the attribute NONCE from the element.
func (e *MathMLMUNDERElement) NONCERemove() *MathMLMUNDERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("nonce")
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLMUNDERElement) SCRIPTLEVEL(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("scriptlevel", i)
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLMUNDERElement) IfSCRIPTLEVEL(condition bool, i int) *MathMLMUNDERElement {
	if condition {
		e.SCRIPTLEVEL(i)
	}
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
// Remove the attribute SCRIPTLEVEL from the element.
func (e *MathMLMUNDERElement) SCRIPTLEVELRemove() *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("scriptlevel")
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLEPairs(pairs ...string) *MathMLMUNDERElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLE(s string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLE(condition bool, s string) *MathMLMUNDERElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLEAdd(k string, v string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) STYLEAddF(k string, format string, args ...any) *MathMLMUNDERElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLEAdd(condition bool, k string, v string) *MathMLMUNDERElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMUNDERElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *MathMLMUNDERElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
//
// Add the attributes in the map to the element.
func (e *MathMLMUNDERElement) STYLEMap(m map[string]string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Remove the attribute STYLE from the element.
func (e *MathMLMUNDERElement) STYLERemove(keys ...string) *MathMLMUNDERElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLMUNDERElement) TABINDEX(i int) *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("tabindex", i)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLMUNDERElement) IfTABINDEX(condition bool, i int) *MathMLMUNDERElement {
	if condition {
		e.TABINDEX(i)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
// Remove the attribute TABINDEX from the element.
func (e *MathMLMUNDERElement) TABINDEXRemove() *MathMLMUNDERElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("tabindex")
	return e
}
