// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T23:50:51+01:00

// package mathml semantics is generated from configuration file.
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// This element is used to specify the meaning of a MathML expression.
type MathMLSEMANTICSElement struct {
	*Element
}

// Create a new MathMLSEMANTICSElement element.
// This will create a new element with the tag
// "semantics" during rendering.
func MathML_SEMANTICS(children ...ElementRenderer) *MathMLSEMANTICSElement {
	e := NewElement("semantics", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &MathMLSEMANTICSElement{Element: e}
}

func (e *MathMLSEMANTICSElement) Children(children ...ElementRenderer) *MathMLSEMANTICSElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *MathMLSEMANTICSElement) IfChildren(condition bool, children ...ElementRenderer) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *MathMLSEMANTICSElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *MathMLSEMANTICSElement) BoolAttr(name string) *MathMLSEMANTICSElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *MathMLSEMANTICSElement) IfBoolAttr(condition bool, name string) *MathMLSEMANTICSElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *MathMLSEMANTICSElement) Attr(name, value string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *MathMLSEMANTICSElement) IfAttr(condition bool, name, value string) *MathMLSEMANTICSElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *MathMLSEMANTICSElement) Text(text string) *MathMLSEMANTICSElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *MathMLSEMANTICSElement) TextF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *MathMLSEMANTICSElement) IfText(condition bool, text string) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *MathMLSEMANTICSElement) IfTextF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *MathMLSEMANTICSElement) Escaped(text string) *MathMLSEMANTICSElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *MathMLSEMANTICSElement) IfEscaped(condition bool, text string) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *MathMLSEMANTICSElement) EscapedF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *MathMLSEMANTICSElement) IfEscapedF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *MathMLSEMANTICSElement) CustomData(key, value string) *MathMLSEMANTICSElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *MathMLSEMANTICSElement) IfCustomData(condition bool, key, value string) *MathMLSEMANTICSElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *MathMLSEMANTICSElement) CustomDataF(key, format string, args ...any) *MathMLSEMANTICSElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *MathMLSEMANTICSElement) IfCustomDataF(condition bool, key, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *MathMLSEMANTICSElement) CustomDataRemove(key string) *MathMLSEMANTICSElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLSEMANTICSElement) CLASS(s ...string) *MathMLSEMANTICSElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLSEMANTICSElement) IfCLASS(condition bool, s ...string) *MathMLSEMANTICSElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
// Remove the attribute CLASS from the element.
func (e *MathMLSEMANTICSElement) CLASSRemove(s ...string) *MathMLSEMANTICSElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
func (e *MathMLSEMANTICSElement) DIR(c MathMLSemanticsDirChoice) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dir", string(c))
	return e
}

type MathMLSemanticsDirChoice string

const (
	// left-to-right
	MathMLSemanticsDir_ltr MathMLSemanticsDirChoice = "ltr"
	// right-to-left
	MathMLSemanticsDir_rtl MathMLSemanticsDirChoice = "rtl"
)

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
// Remove the attribute DIR from the element.
func (e *MathMLSEMANTICSElement) DIRRemove(c MathMLSemanticsDirChoice) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dir")
	return e
}

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
func (e *MathMLSEMANTICSElement) DISPLAYSTYLE(c MathMLSemanticsDisplaystyleChoice) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("displaystyle", string(c))
	return e
}

type MathMLSemanticsDisplaystyleChoice string

const (
	// displaystyle rules
	MathMLSemanticsDisplaystyle_true MathMLSemanticsDisplaystyleChoice = "true"
	// not displaystyle rules
	MathMLSemanticsDisplaystyle_false MathMLSemanticsDisplaystyleChoice = "false"
)

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
// Remove the attribute DISPLAYSTYLE from the element.
func (e *MathMLSEMANTICSElement) DISPLAYSTYLERemove(c MathMLSemanticsDisplaystyleChoice) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("displaystyle")
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLSEMANTICSElement) ID(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLSEMANTICSElement) IDF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLSEMANTICSElement) IfID(condition bool, s string) *MathMLSEMANTICSElement {
	if condition {
		e.ID(s)
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLSEMANTICSElement) IfIDF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
// Remove the attribute ID from the element.
func (e *MathMLSEMANTICSElement) IDRemove(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLSEMANTICSElement) IDRemoveF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHBACKGROUND(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathbackground", s)
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHBACKGROUNDF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHBACKGROUND(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) IfMATHBACKGROUND(condition bool, s string) *MathMLSEMANTICSElement {
	if condition {
		e.MATHBACKGROUND(s)
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) IfMATHBACKGROUNDF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.MATHBACKGROUND(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
// Remove the attribute MATHBACKGROUND from the element.
func (e *MathMLSEMANTICSElement) MATHBACKGROUNDRemove(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathbackground")
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHBACKGROUNDRemoveF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHBACKGROUNDRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHCOLOR(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathcolor", s)
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHCOLORF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHCOLOR(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) IfMATHCOLOR(condition bool, s string) *MathMLSEMANTICSElement {
	if condition {
		e.MATHCOLOR(s)
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) IfMATHCOLORF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.MATHCOLOR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
// Remove the attribute MATHCOLOR from the element.
func (e *MathMLSEMANTICSElement) MATHCOLORRemove(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathcolor")
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLSEMANTICSElement) MATHCOLORRemoveF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHCOLORRemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLSEMANTICSElement) MATHSIZE_STR(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathsize", s)
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLSEMANTICSElement) MATHSIZE_STRF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHSIZE_STR(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLSEMANTICSElement) IfMATHSIZE_STR(condition bool, s string) *MathMLSEMANTICSElement {
	if condition {
		e.MATHSIZE_STR(s)
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLSEMANTICSElement) IfMATHSIZE_STRF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.MATHSIZE_STR(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
// Remove the attribute MATHSIZE_STR from the element.
func (e *MathMLSEMANTICSElement) MATHSIZE_STRRemove(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathsize")
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLSEMANTICSElement) MATHSIZE_STRRemoveF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.MATHSIZE_STRRemove(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLSEMANTICSElement) NONCE(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("nonce", s)
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLSEMANTICSElement) NONCEF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.NONCE(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLSEMANTICSElement) IfNONCE(condition bool, s string) *MathMLSEMANTICSElement {
	if condition {
		e.NONCE(s)
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLSEMANTICSElement) IfNONCEF(condition bool, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.NONCE(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
// Remove the attribute NONCE from the element.
func (e *MathMLSEMANTICSElement) NONCERemove(s string) *MathMLSEMANTICSElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("nonce")
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLSEMANTICSElement) NONCERemoveF(format string, args ...any) *MathMLSEMANTICSElement {
	return e.NONCERemove(fmt.Sprintf(format, args...))
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLSEMANTICSElement) SCRIPTLEVEL(i int) *MathMLSEMANTICSElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("scriptlevel", i)
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLSEMANTICSElement) IfSCRIPTLEVEL(condition bool, i int) *MathMLSEMANTICSElement {
	if condition {
		e.SCRIPTLEVEL(i)
	}
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
// Remove the attribute SCRIPTLEVEL from the element.
func (e *MathMLSEMANTICSElement) SCRIPTLEVELRemove(i int) *MathMLSEMANTICSElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("scriptlevel")
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLSEMANTICSElement) STYLEF(k string, format string, args ...any) *MathMLSEMANTICSElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLSEMANTICSElement) IfSTYLE(condition bool, k string, v string) *MathMLSEMANTICSElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLSEMANTICSElement) STYLE(k string, v string) *MathMLSEMANTICSElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLSEMANTICSElement) IfSTYLEF(condition bool, k string, format string, args ...any) *MathMLSEMANTICSElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Add the attributes in the map to the element.
func (e *MathMLSEMANTICSElement) STYLEMap(m map[string]string) *MathMLSEMANTICSElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Remove the attribute STYLE from the element.
func (e *MathMLSEMANTICSElement) STYLERemove(keys ...string) *MathMLSEMANTICSElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLSEMANTICSElement) TABINDEX(i int) *MathMLSEMANTICSElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("tabindex", i)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLSEMANTICSElement) IfTABINDEX(condition bool, i int) *MathMLSEMANTICSElement {
	if condition {
		e.TABINDEX(i)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
// Remove the attribute TABINDEX from the element.
func (e *MathMLSEMANTICSElement) TABINDEXRemove(i int) *MathMLSEMANTICSElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("tabindex")
	return e
}
