// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feMerge is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feMerge> SVG element allows filter effects to be applied concurrently
// instead of sequentially.
type SVGFEMERGEElement struct {
	*Element
}

// Create a new SVGFEMERGEElement element.
// This will create a new element with the tag
// "feMerge" during rendering.
func SVG_FEMERGE(children ...ElementRenderer) *SVGFEMERGEElement {
	e := NewElement("feMerge", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEMERGEElement{Element: e}
}

func (e *SVGFEMERGEElement) Children(children ...ElementRenderer) *SVGFEMERGEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEMERGEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEMERGEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEMERGEElement) BoolAttr(name string) *SVGFEMERGEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEMERGEElement) IfBoolAttr(condition bool, name string) *SVGFEMERGEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEMERGEElement) Attr(name, value string) *SVGFEMERGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEMERGEElement) IfAttr(condition bool, name, value string) *SVGFEMERGEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEMERGEElement) Text(text string) *SVGFEMERGEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEMERGEElement) TextF(format string, args ...any) *SVGFEMERGEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGEElement) IfText(condition bool, text string) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEMERGEElement) IfTextF(condition bool, format string, args ...any) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEMERGEElement) Escaped(text string) *SVGFEMERGEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEMERGEElement) IfEscaped(condition bool, text string) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEMERGEElement) EscapedF(format string, args ...any) *SVGFEMERGEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGEElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEMERGEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEMERGEElement) CustomData(key, value string) *SVGFEMERGEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEMERGEElement) IfCustomData(condition bool, key, value string) *SVGFEMERGEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEMERGEElement) CustomDataF(key, format string, args ...any) *SVGFEMERGEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEMERGEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEMERGEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEMERGEElement) CustomDataRemove(key string) *SVGFEMERGEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEMERGEElement) ID(s string) *SVGFEMERGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEMERGEElement) IDF(format string, args ...any) *SVGFEMERGEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEMERGEElement) IfID(condition bool, s string) *SVGFEMERGEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEMERGEElement) IfIDF(condition bool, format string, args ...any) *SVGFEMERGEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFEMERGEElement) IDRemove() *SVGFEMERGEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEMERGEElement) CLASS(s string) *SVGFEMERGEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEMERGEElement) IfCLASS(condition bool, s string) *SVGFEMERGEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFEMERGEElement) CLASSRemove(s ...string) *SVGFEMERGEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) STYLEPairs(pairs ...string) *SVGFEMERGEElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) STYLE(s string) *SVGFEMERGEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) IfSTYLE(condition bool, s string) *SVGFEMERGEElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) STYLEAdd(k string, v string) *SVGFEMERGEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) STYLEAddF(k string, format string, args ...any) *SVGFEMERGEElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFEMERGEElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEMERGEElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFEMERGEElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFEMERGEElement) STYLEMap(m map[string]string) *SVGFEMERGEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEMERGEElement) STYLERemove(keys ...string) *SVGFEMERGEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
