// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T15:01:36+01:00

// package svg fePointLight is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <fePointLight> SVG filter primitive defines a light source at a point on
// the plane of the user coordinate system.
type SVGFEPOINTLIGHTElement struct {
	*Element
}

// Create a new SVGFEPOINTLIGHTElement element.
// This will create a new element with the tag
// "fePointLight" during rendering.
func SVG_FEPOINTLIGHT(children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	e := NewElement("fePointLight", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEPOINTLIGHTElement{Element: e}
}

func (e *SVGFEPOINTLIGHTElement) Children(children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) BoolAttr(name string) *SVGFEPOINTLIGHTElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfBoolAttr(condition bool, name string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Attr(name, value string) *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfAttr(condition bool, name, value string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Text(text string) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEPOINTLIGHTElement) TextF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfText(condition bool, text string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfTextF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Escaped(text string) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfEscaped(condition bool, text string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) EscapedF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomData(key, value string) *SVGFEPOINTLIGHTElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfCustomData(condition bool, key, value string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomDataF(key, format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomDataRemove(key string) *SVGFEPOINTLIGHTElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x attribute indicates the x location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) X(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

// The x attribute indicates the x location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfX(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y attribute indicates the y location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) Y(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

// The y attribute indicates the y location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfY(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The z attribute indicates the z location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) Z(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("z", f)
	return e
}

// The z attribute indicates the z location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfZ(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Z(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) ID(s string) *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IDF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IfID(condition bool, s string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IfIDF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFEPOINTLIGHTElement) IDRemove(s string) *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IDRemoveF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEPOINTLIGHTElement) CLASS(s ...string) *SVGFEPOINTLIGHTElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEPOINTLIGHTElement) IfCLASS(condition bool, s ...string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGFEPOINTLIGHTElement) CLASSRemove(s ...string) *SVGFEPOINTLIGHTElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLEF(k string, format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) IfSTYLE(condition bool, k string, v string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLE(k string, v string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFEPOINTLIGHTElement) STYLEMap(m map[string]string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEPOINTLIGHTElement) STYLERemove(keys ...string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
