// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg feOffset is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <feOffset> SVG filter primitive allows to offset the input image. The
// amount of offset can be controlled by attributes dx and dy.
type SVGFEOFFSETElement struct {
	*Element
}

// Create a new SVGFEOFFSETElement element.
// This will create a new element with the tag
// "feOffset" during rendering.
func SVG_FEOFFSET(children ...ElementRenderer) *SVGFEOFFSETElement {
	e := NewElement("feOffset", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEOFFSETElement{Element: e}
}

func (e *SVGFEOFFSETElement) Children(children ...ElementRenderer) *SVGFEOFFSETElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEOFFSETElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEOFFSETElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEOFFSETElement) BoolAttr(name string) *SVGFEOFFSETElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEOFFSETElement) IfBoolAttr(condition bool, name string) *SVGFEOFFSETElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEOFFSETElement) Attr(name, value string) *SVGFEOFFSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEOFFSETElement) IfAttr(condition bool, name, value string) *SVGFEOFFSETElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEOFFSETElement) Attrs(attrs ...string) *SVGFEOFFSETElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFEOFFSETElement) AttrsMap(attrs map[string]string) *SVGFEOFFSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFEOFFSETElement) Text(text string) *SVGFEOFFSETElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEOFFSETElement) TextF(format string, args ...any) *SVGFEOFFSETElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEOFFSETElement) IfText(condition bool, text string) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEOFFSETElement) IfTextF(condition bool, format string, args ...any) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEOFFSETElement) Escaped(text string) *SVGFEOFFSETElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEOFFSETElement) IfEscaped(condition bool, text string) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEOFFSETElement) EscapedF(format string, args ...any) *SVGFEOFFSETElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEOFFSETElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEOFFSETElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEOFFSETElement) CustomData(key, value string) *SVGFEOFFSETElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEOFFSETElement) IfCustomData(condition bool, key, value string) *SVGFEOFFSETElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEOFFSETElement) CustomDataF(key, format string, args ...any) *SVGFEOFFSETElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEOFFSETElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEOFFSETElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEOFFSETElement) CustomDataRemove(key string) *SVGFEOFFSETElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The dx attribute indicates a shift along the x-axis on the kernel matrix.
func (e *SVGFEOFFSETElement) DX(f float64) *SVGFEOFFSETElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dx", f)
	return e
}

// The dx attribute indicates a shift along the x-axis on the kernel matrix.
func (e *SVGFEOFFSETElement) IfDX(condition bool, f float64) *SVGFEOFFSETElement {
	if condition {
		e.DX(f)
	}
	return e
}

// The dy attribute indicates a shift along the y-axis on the kernel matrix.
func (e *SVGFEOFFSETElement) DY(f float64) *SVGFEOFFSETElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dy", f)
	return e
}

// The dy attribute indicates a shift along the y-axis on the kernel matrix.
func (e *SVGFEOFFSETElement) IfDY(condition bool, f float64) *SVGFEOFFSETElement {
	if condition {
		e.DY(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEOFFSETElement) ID(s string) *SVGFEOFFSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEOFFSETElement) IDF(format string, args ...any) *SVGFEOFFSETElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEOFFSETElement) IfID(condition bool, s string) *SVGFEOFFSETElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEOFFSETElement) IfIDF(condition bool, format string, args ...any) *SVGFEOFFSETElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFEOFFSETElement) IDRemove(s string) *SVGFEOFFSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGFEOFFSETElement) IDRemoveF(format string, args ...any) *SVGFEOFFSETElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEOFFSETElement) CLASS(s ...string) *SVGFEOFFSETElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEOFFSETElement) IfCLASS(condition bool, s ...string) *SVGFEOFFSETElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGFEOFFSETElement) CLASSRemove(s ...string) *SVGFEOFFSETElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEOFFSETElement) STYLEF(k string, format string, args ...any) *SVGFEOFFSETElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEOFFSETElement) IfSTYLE(condition bool, k string, v string) *SVGFEOFFSETElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEOFFSETElement) STYLE(k string, v string) *SVGFEOFFSETElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEOFFSETElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFEOFFSETElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFEOFFSETElement) STYLEMap(m map[string]string) *SVGFEOFFSETElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add pairs of attributes to the element.
func (e *SVGFEOFFSETElement) STYLEPairs(pairs ...string) *SVGFEOFFSETElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEOFFSETElement) IfSTYLEPairs(condition bool, pairs ...string) *SVGFEOFFSETElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEOFFSETElement) STYLERemove(keys ...string) *SVGFEOFFSETElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
