// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg style is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <style> SVG element allows style sheets to be embedded directly within
// SVG content. SVG's style element has the same attributes as the corresponding
// element in HTML (see HTML's <style> element).
type SVGSTYLEElement struct {
	*Element
}

// Create a new SVGSTYLEElement element.
// This will create a new element with the tag
// "style" during rendering.
func SVG_STYLE(children ...ElementRenderer) *SVGSTYLEElement {
	e := NewElement("style", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGSTYLEElement{Element: e}
}

func (e *SVGSTYLEElement) Children(children ...ElementRenderer) *SVGSTYLEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGSTYLEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGSTYLEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGSTYLEElement) BoolAttr(name string) *SVGSTYLEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGSTYLEElement) IfBoolAttr(condition bool, name string) *SVGSTYLEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGSTYLEElement) Attr(name, value string) *SVGSTYLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGSTYLEElement) IfAttr(condition bool, name, value string) *SVGSTYLEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGSTYLEElement) Text(text string) *SVGSTYLEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGSTYLEElement) TextF(format string, args ...any) *SVGSTYLEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGSTYLEElement) IfText(condition bool, text string) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGSTYLEElement) IfTextF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGSTYLEElement) Escaped(text string) *SVGSTYLEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGSTYLEElement) IfEscaped(condition bool, text string) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGSTYLEElement) EscapedF(format string, args ...any) *SVGSTYLEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGSTYLEElement) IfEscapedF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGSTYLEElement) CustomData(key, value string) *SVGSTYLEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGSTYLEElement) IfCustomData(condition bool, key, value string) *SVGSTYLEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGSTYLEElement) CustomDataF(key, format string, args ...any) *SVGSTYLEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGSTYLEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGSTYLEElement) CustomDataRemove(key string) *SVGSTYLEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The style sheet language.
func (e *SVGSTYLEElement) TYPE(s string) *SVGSTYLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("type", s)
	return e
}

// The style sheet language.
func (e *SVGSTYLEElement) TYPEF(format string, args ...any) *SVGSTYLEElement {
	return e.TYPE(fmt.Sprintf(format, args...))
}

// The style sheet language.
func (e *SVGSTYLEElement) IfTYPE(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.TYPE(s)
	}
	return e
}

// The style sheet language.
func (e *SVGSTYLEElement) IfTYPEF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.TYPE(fmt.Sprintf(format, args...))
	}
	return e
}

// The style sheet language.
//
// Remove the attribute TYPE from the element.
func (e *SVGSTYLEElement) TYPERemove() *SVGSTYLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("type")
	return e
}

// The intended destination medium for style information.
func (e *SVGSTYLEElement) MEDIA(s string) *SVGSTYLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("media", s)
	return e
}

// The intended destination medium for style information.
func (e *SVGSTYLEElement) MEDIAF(format string, args ...any) *SVGSTYLEElement {
	return e.MEDIA(fmt.Sprintf(format, args...))
}

// The intended destination medium for style information.
func (e *SVGSTYLEElement) IfMEDIA(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.MEDIA(s)
	}
	return e
}

// The intended destination medium for style information.
func (e *SVGSTYLEElement) IfMEDIAF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.MEDIA(fmt.Sprintf(format, args...))
	}
	return e
}

// The intended destination medium for style information.
//
// Remove the attribute MEDIA from the element.
func (e *SVGSTYLEElement) MEDIARemove() *SVGSTYLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("media")
	return e
}

// The advisory title.
func (e *SVGSTYLEElement) TITLE(s string) *SVGSTYLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("title", s)
	return e
}

// The advisory title.
func (e *SVGSTYLEElement) TITLEF(format string, args ...any) *SVGSTYLEElement {
	return e.TITLE(fmt.Sprintf(format, args...))
}

// The advisory title.
func (e *SVGSTYLEElement) IfTITLE(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.TITLE(s)
	}
	return e
}

// The advisory title.
func (e *SVGSTYLEElement) IfTITLEF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.TITLE(fmt.Sprintf(format, args...))
	}
	return e
}

// The advisory title.
//
// Remove the attribute TITLE from the element.
func (e *SVGSTYLEElement) TITLERemove() *SVGSTYLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("title")
	return e
}

// Specifies a unique id for an element
func (e *SVGSTYLEElement) ID(s string) *SVGSTYLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGSTYLEElement) IDF(format string, args ...any) *SVGSTYLEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGSTYLEElement) IfID(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGSTYLEElement) IfIDF(condition bool, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGSTYLEElement) IDRemove() *SVGSTYLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGSTYLEElement) CLASS(s string) *SVGSTYLEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGSTYLEElement) IfCLASS(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGSTYLEElement) CLASSRemove(s ...string) *SVGSTYLEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) STYLEPairs(pairs ...string) *SVGSTYLEElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) STYLE(s string) *SVGSTYLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) IfSTYLE(condition bool, s string) *SVGSTYLEElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) STYLEAdd(k string, v string) *SVGSTYLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) STYLEAddF(k string, format string, args ...any) *SVGSTYLEElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) IfSTYLEAdd(condition bool, k string, v string) *SVGSTYLEElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSTYLEElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGSTYLEElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGSTYLEElement) STYLEMap(m map[string]string) *SVGSTYLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGSTYLEElement) STYLERemove(keys ...string) *SVGSTYLEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
