// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feDropShadow is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feDropShadow> filter primitive creates a drop shadow of the input image.
// It is a shorthand filter, and is defined in terms of the <feGaussianBlur> and
// <feOffset> filter primitives.
type SVGFEDROPSHADOWElement struct {
	*Element
}

// Create a new SVGFEDROPSHADOWElement element.
// This will create a new element with the tag
// "feDropShadow" during rendering.
func SVG_FEDROPSHADOW(children ...ElementRenderer) *SVGFEDROPSHADOWElement {
	e := NewElement("feDropShadow", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEDROPSHADOWElement{Element: e}
}

func (e *SVGFEDROPSHADOWElement) Children(children ...ElementRenderer) *SVGFEDROPSHADOWElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEDROPSHADOWElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) BoolAttr(name string) *SVGFEDROPSHADOWElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEDROPSHADOWElement) IfBoolAttr(condition bool, name string) *SVGFEDROPSHADOWElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) Attr(name, value string) *SVGFEDROPSHADOWElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEDROPSHADOWElement) IfAttr(condition bool, name, value string) *SVGFEDROPSHADOWElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) Text(text string) *SVGFEDROPSHADOWElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEDROPSHADOWElement) TextF(format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEDROPSHADOWElement) IfText(condition bool, text string) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) IfTextF(condition bool, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) Escaped(text string) *SVGFEDROPSHADOWElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEDROPSHADOWElement) IfEscaped(condition bool, text string) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) EscapedF(format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEDROPSHADOWElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) CustomData(key, value string) *SVGFEDROPSHADOWElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEDROPSHADOWElement) IfCustomData(condition bool, key, value string) *SVGFEDROPSHADOWElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) CustomDataF(key, format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEDROPSHADOWElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEDROPSHADOWElement) CustomDataRemove(key string) *SVGFEDROPSHADOWElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The amount of offset in the x direction. If the <length> is 0, the shadow is
// placed at the same position as the input.
func (e *SVGFEDROPSHADOWElement) DX(f float64) *SVGFEDROPSHADOWElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dx", f)
	return e
}

// The amount of offset in the x direction. If the <length> is 0, the shadow is
// placed at the same position as the input.
func (e *SVGFEDROPSHADOWElement) IfDX(condition bool, f float64) *SVGFEDROPSHADOWElement {
	if condition {
		e.DX(f)
	}
	return e
}

// The amount of offset in the y direction. If the <length> is 0, the shadow is
// placed at the same position as the input.
func (e *SVGFEDROPSHADOWElement) DY(f float64) *SVGFEDROPSHADOWElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dy", f)
	return e
}

// The amount of offset in the y direction. If the <length> is 0, the shadow is
// placed at the same position as the input.
func (e *SVGFEDROPSHADOWElement) IfDY(condition bool, f float64) *SVGFEDROPSHADOWElement {
	if condition {
		e.DY(f)
	}
	return e
}

// The standard deviation for the blur operation. If two <numbers> are provided,
// the first number represents a standard deviation value along the x-axis of
// the coordinate system established by attribute 'primitiveUnits' on the
// <filter> element. The second value represents a standard deviation in Y. If
// one number is provided, then that value is used for both X and Y. Negative
// values are not allowed. A value of zero disables the effect of the given
// filter primitive (i.e., the result is a transparent black image).
func (e *SVGFEDROPSHADOWElement) STD_DEVIATION(f float64) *SVGFEDROPSHADOWElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("stdDeviation", f)
	return e
}

// The standard deviation for the blur operation. If two <numbers> are provided,
// the first number represents a standard deviation value along the x-axis of
// the coordinate system established by attribute 'primitiveUnits' on the
// <filter> element. The second value represents a standard deviation in Y. If
// one number is provided, then that value is used for both X and Y. Negative
// values are not allowed. A value of zero disables the effect of the given
// filter primitive (i.e., the result is a transparent black image).
func (e *SVGFEDROPSHADOWElement) IfSTD_DEVIATION(condition bool, f float64) *SVGFEDROPSHADOWElement {
	if condition {
		e.STD_DEVIATION(f)
	}
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEDROPSHADOWElement) FLOOD_COLOR(s string) *SVGFEDROPSHADOWElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("flood-color", s)
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEDROPSHADOWElement) FLOOD_COLORF(format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.FLOOD_COLOR(fmt.Sprintf(format, args...))
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEDROPSHADOWElement) IfFLOOD_COLOR(condition bool, s string) *SVGFEDROPSHADOWElement {
	if condition {
		e.FLOOD_COLOR(s)
	}
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEDROPSHADOWElement) IfFLOOD_COLORF(condition bool, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.FLOOD_COLOR(fmt.Sprintf(format, args...))
	}
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
//
// Remove the attribute FLOOD_COLOR from the element.
func (e *SVGFEDROPSHADOWElement) FLOOD_COLORRemove() *SVGFEDROPSHADOWElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("flood-color")
	return e
}

// The flood-opacity attribute indicates the opacity value to use across the
// current filter primitive subregion defined through the <feFlood> element.
func (e *SVGFEDROPSHADOWElement) FLOOD_OPACITY(f float64) *SVGFEDROPSHADOWElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("flood-opacity", f)
	return e
}

// The flood-opacity attribute indicates the opacity value to use across the
// current filter primitive subregion defined through the <feFlood> element.
func (e *SVGFEDROPSHADOWElement) IfFLOOD_OPACITY(condition bool, f float64) *SVGFEDROPSHADOWElement {
	if condition {
		e.FLOOD_OPACITY(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDROPSHADOWElement) ID(s string) *SVGFEDROPSHADOWElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDROPSHADOWElement) IDF(format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEDROPSHADOWElement) IfID(condition bool, s string) *SVGFEDROPSHADOWElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDROPSHADOWElement) IfIDF(condition bool, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFEDROPSHADOWElement) IDRemove() *SVGFEDROPSHADOWElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEDROPSHADOWElement) CLASS(s string) *SVGFEDROPSHADOWElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEDROPSHADOWElement) IfCLASS(condition bool, s string) *SVGFEDROPSHADOWElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFEDROPSHADOWElement) CLASSRemove(s ...string) *SVGFEDROPSHADOWElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) STYLEPairs(pairs ...string) *SVGFEDROPSHADOWElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) STYLE(s string) *SVGFEDROPSHADOWElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) IfSTYLE(condition bool, s string) *SVGFEDROPSHADOWElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) STYLEAdd(k string, v string) *SVGFEDROPSHADOWElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) STYLEAddF(k string, format string, args ...any) *SVGFEDROPSHADOWElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFEDROPSHADOWElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDROPSHADOWElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFEDROPSHADOWElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFEDROPSHADOWElement) STYLEMap(m map[string]string) *SVGFEDROPSHADOWElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEDROPSHADOWElement) STYLERemove(keys ...string) *SVGFEDROPSHADOWElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
