// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED.
// package svg tspan is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <tspan> SVG element lets authors explicitly specify the location of a
// glyph along the given path via the attributes.
type SVGTSPANElement struct {
	*Element
}

// Create a new SVGTSPANElement element.
// This will create a new element with the tag
// "tspan" during rendering.
func SVG_TSPAN(children ...ElementRenderer) *SVGTSPANElement {
	e := NewElement("tspan", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGTSPANElement{Element: e}
}

func (e *SVGTSPANElement) Children(children ...ElementRenderer) *SVGTSPANElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGTSPANElement) IfChildren(condition bool, children ...ElementRenderer) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGTSPANElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGTSPANElement) BoolAttr(name string) *SVGTSPANElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGTSPANElement) IfBoolAttr(condition bool, name string) *SVGTSPANElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGTSPANElement) Attr(name, value string) *SVGTSPANElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGTSPANElement) IfAttr(condition bool, name, value string) *SVGTSPANElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGTSPANElement) Attrs(attrs ...string) *SVGTSPANElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGTSPANElement) AttrsMap(attrs map[string]string) *SVGTSPANElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.StringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGTSPANElement) Text(text string) *SVGTSPANElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGTSPANElement) TextF(format string, args ...any) *SVGTSPANElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGTSPANElement) IfText(condition bool, text string) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGTSPANElement) IfTextF(condition bool, format string, args ...any) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGTSPANElement) Escaped(text string) *SVGTSPANElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGTSPANElement) IfEscaped(condition bool, text string) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGTSPANElement) EscapedF(format string, args ...any) *SVGTSPANElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGTSPANElement) IfEscapedF(condition bool, format string, args ...any) *SVGTSPANElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGTSPANElement) CustomData(key, value string) *SVGTSPANElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGTSPANElement) IfCustomData(condition bool, key, value string) *SVGTSPANElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGTSPANElement) CustomDataF(key, format string, args ...any) *SVGTSPANElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGTSPANElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGTSPANElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGTSPANElement) CustomDataRemove(key string) *SVGTSPANElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x-axis coordinate of the current text position.
func (e *SVGTSPANElement) X(f float64) *SVGTSPANElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

// The x-axis coordinate of the current text position.
func (e *SVGTSPANElement) IfX(condition bool, f float64) *SVGTSPANElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y-axis coordinate of the current text position.
func (e *SVGTSPANElement) Y(f float64) *SVGTSPANElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

// The y-axis coordinate of the current text position.
func (e *SVGTSPANElement) IfY(condition bool, f float64) *SVGTSPANElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The x-axis coordinate of the current text position.
func (e *SVGTSPANElement) DX(f float64) *SVGTSPANElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dx", f)
	return e
}

// The x-axis coordinate of the current text position.
func (e *SVGTSPANElement) IfDX(condition bool, f float64) *SVGTSPANElement {
	if condition {
		e.DX(f)
	}
	return e
}

// The y-axis coordinate of the current text position.
func (e *SVGTSPANElement) DY(f float64) *SVGTSPANElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("dy", f)
	return e
}

// The y-axis coordinate of the current text position.
func (e *SVGTSPANElement) IfDY(condition bool, f float64) *SVGTSPANElement {
	if condition {
		e.DY(f)
	}
	return e
}

// The rotation angle about the current text position.
func (e *SVGTSPANElement) ROTATE(f float64) *SVGTSPANElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("rotate", f)
	return e
}

// The rotation angle about the current text position.
func (e *SVGTSPANElement) IfROTATE(condition bool, f float64) *SVGTSPANElement {
	if condition {
		e.ROTATE(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGTSPANElement) ID(s string) *SVGTSPANElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGTSPANElement) IDF(format string, args ...any) *SVGTSPANElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGTSPANElement) IfID(condition bool, s string) *SVGTSPANElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGTSPANElement) IfIDF(condition bool, format string, args ...any) *SVGTSPANElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGTSPANElement) IDRemove(s string) *SVGTSPANElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGTSPANElement) IDRemoveF(format string, args ...any) *SVGTSPANElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGTSPANElement) CLASS(s ...string) *SVGTSPANElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGTSPANElement) IfCLASS(condition bool, s ...string) *SVGTSPANElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGTSPANElement) CLASSRemove(s ...string) *SVGTSPANElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTSPANElement) STYLEF(k string, format string, args ...any) *SVGTSPANElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGTSPANElement) IfSTYLE(condition bool, k string, v string) *SVGTSPANElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTSPANElement) STYLE(k string, v string) *SVGTSPANElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTSPANElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGTSPANElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGTSPANElement) STYLEMap(m map[string]string) *SVGTSPANElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add pairs of attributes to the element.
func (e *SVGTSPANElement) STYLEPairs(pairs ...string) *SVGTSPANElement {
	if len(pairs)%2 != 0 {
		panic("Must have an even number of pairs")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}

	for i := 0; i < len(pairs); i += 2 {
		kv.Add(pairs[i], pairs[i+1])
	}

	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTSPANElement) IfSTYLEPairs(condition bool, pairs ...string) *SVGTSPANElement {
	if condition {
		e.STYLEPairs(pairs...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGTSPANElement) STYLERemove(keys ...string) *SVGTSPANElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
