// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-03T23:53:57+01:00

// package svg image is generated from configuration file.
package elements

import (
	"fmt"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <image> SVG element includes images inside SVG documents.
type SVGIMAGEElement struct {
	*Element
}

// Create a new SVGIMAGEElement element.
// This will create a new element with the tag
// "image" during rendering.
func SVG_IMAGE(children ...ElementRenderer) *SVGIMAGEElement {
	e := NewElement("image", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGIMAGEElement{Element: e}
}

func (e *SVGIMAGEElement) Children(children ...ElementRenderer) *SVGIMAGEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGIMAGEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGIMAGEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGIMAGEElement) BoolAttr(name string) *SVGIMAGEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGIMAGEElement) IfBoolAttr(condition bool, name string) *SVGIMAGEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGIMAGEElement) Attr(name, value string) *SVGIMAGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGIMAGEElement) IfAttr(condition bool, name, value string) *SVGIMAGEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGIMAGEElement) Text(text string) *SVGIMAGEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGIMAGEElement) TextF(format string, args ...any) *SVGIMAGEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGIMAGEElement) IfText(condition bool, text string) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGIMAGEElement) IfTextF(condition bool, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGIMAGEElement) Escaped(text string) *SVGIMAGEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGIMAGEElement) IfEscaped(condition bool, text string) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGIMAGEElement) EscapedF(format string, args ...any) *SVGIMAGEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGIMAGEElement) IfEscapedF(condition bool, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGIMAGEElement) CustomData(key, value string) *SVGIMAGEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGIMAGEElement) IfCustomData(condition bool, key, value string) *SVGIMAGEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGIMAGEElement) CustomDataF(key, format string, args ...any) *SVGIMAGEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGIMAGEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGIMAGEElement) CustomDataRemove(key string) *SVGIMAGEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Indicates how the fetched image is fitted into the destination rectangle.
func (e *SVGIMAGEElement) PRESERVE_ASPECT_RATIO(c SVGImagePreserveAspectRatioChoice) *SVGIMAGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("preserveAspectRatio", string(c))
	return e
}

type SVGImagePreserveAspectRatioChoice string

const (
	// Do not force uniform scaling.
	SVGImagePreserveAspectRatio_none SVGImagePreserveAspectRatioChoice = "none"
	// Scale the image to the smallest size such that both its width and its height
	// can completely fit inside the corresponding dimension of the viewPort.
	SVGImagePreserveAspectRatio_xMinYMin SVGImagePreserveAspectRatioChoice = "xMinYMin"
	// Align the image along the middle of the corresponding dimension of the
	// viewPort.
	SVGImagePreserveAspectRatio_xMidYMin SVGImagePreserveAspectRatioChoice = "xMidYMin"
	// Align the image with the corresponding side of the viewPort.
	SVGImagePreserveAspectRatio_xMaxYMin SVGImagePreserveAspectRatioChoice = "xMaxYMin"
	// Align the image along the middle of the corresponding dimension of the
	// viewPort.
	SVGImagePreserveAspectRatio_xMinYMid SVGImagePreserveAspectRatioChoice = "xMinYMid"
	// Scale the image to the smallest size such that it can completely fit inside
	// the corresponding dimension of the viewPort.
	SVGImagePreserveAspectRatio_xMidYMid SVGImagePreserveAspectRatioChoice = "xMidYMid"
	// Align the image with the corresponding side of the viewPort.
	SVGImagePreserveAspectRatio_xMaxYMid SVGImagePreserveAspectRatioChoice = "xMaxYMid"
	// Align the image along the middle of the corresponding dimension of the
	// viewPort.
	SVGImagePreserveAspectRatio_xMinYMax SVGImagePreserveAspectRatioChoice = "xMinYMax"
	// Align the image with the corresponding side of the viewPort.
	SVGImagePreserveAspectRatio_xMidYMax SVGImagePreserveAspectRatioChoice = "xMidYMax"
	// Scale the image to the smallest size such that both its width and its height
	// can completely fit inside the corresponding dimension of the viewPort.
	SVGImagePreserveAspectRatio_xMaxYMax SVGImagePreserveAspectRatioChoice = "xMaxYMax"
)

// Indicates how the fetched image is fitted into the destination rectangle.
// Remove the attribute PRESERVE_ASPECT_RATIO from the element.
func (e *SVGIMAGEElement) PRESERVE_ASPECT_RATIORemove() *SVGIMAGEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("preserveAspectRatio")
	return e
}

// The x-axis coordinate of the side of the rectangular region which is closest
// to the user.
func (e *SVGIMAGEElement) X(f float64) *SVGIMAGEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

// The x-axis coordinate of the side of the rectangular region which is closest
// to the user.
func (e *SVGIMAGEElement) IfX(condition bool, f float64) *SVGIMAGEElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y-axis coordinate of the side of the rectangular region which is closest
// to the user.
func (e *SVGIMAGEElement) Y(f float64) *SVGIMAGEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

// The y-axis coordinate of the side of the rectangular region which is closest
// to the user.
func (e *SVGIMAGEElement) IfY(condition bool, f float64) *SVGIMAGEElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The width of the rectangular region.
func (e *SVGIMAGEElement) WIDTH(f float64) *SVGIMAGEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("width", f)
	return e
}

// The width of the rectangular region.
func (e *SVGIMAGEElement) IfWIDTH(condition bool, f float64) *SVGIMAGEElement {
	if condition {
		e.WIDTH(f)
	}
	return e
}

// The height of the rectangular region.
func (e *SVGIMAGEElement) HEIGHT(f float64) *SVGIMAGEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("height", f)
	return e
}

// The height of the rectangular region.
func (e *SVGIMAGEElement) IfHEIGHT(condition bool, f float64) *SVGIMAGEElement {
	if condition {
		e.HEIGHT(f)
	}
	return e
}

// A URI reference to the image to embed.
func (e *SVGIMAGEElement) HREF(s string) *SVGIMAGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("href", s)
	return e
}

// A URI reference to the image to embed.
func (e *SVGIMAGEElement) HREFF(format string, args ...any) *SVGIMAGEElement {
	return e.HREF(fmt.Sprintf(format, args...))
}

// A URI reference to the image to embed.
func (e *SVGIMAGEElement) IfHREF(condition bool, s string) *SVGIMAGEElement {
	if condition {
		e.HREF(s)
	}
	return e
}

// A URI reference to the image to embed.
func (e *SVGIMAGEElement) IfHREFF(condition bool, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.HREF(fmt.Sprintf(format, args...))
	}
	return e
}

// A URI reference to the image to embed.
//
// Remove the attribute HREF from the element.
func (e *SVGIMAGEElement) HREFRemove() *SVGIMAGEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("href")
	return e
}

// Specifies a unique id for an element
func (e *SVGIMAGEElement) ID(s string) *SVGIMAGEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGIMAGEElement) IDF(format string, args ...any) *SVGIMAGEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGIMAGEElement) IfID(condition bool, s string) *SVGIMAGEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGIMAGEElement) IfIDF(condition bool, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGIMAGEElement) IDRemove() *SVGIMAGEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGIMAGEElement) CLASS(s string) *SVGIMAGEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGIMAGEElement) IfCLASS(condition bool, s string) *SVGIMAGEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGIMAGEElement) CLASSRemove(s ...string) *SVGIMAGEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGIMAGEElement) STYLEF(k string, format string, args ...any) *SVGIMAGEElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGIMAGEElement) IfSTYLE(condition bool, k string, v string) *SVGIMAGEElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGIMAGEElement) STYLE(k string, v string) *SVGIMAGEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGIMAGEElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGIMAGEElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGIMAGEElement) STYLEMap(m map[string]string) *SVGIMAGEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGIMAGEElement) STYLERemove(keys ...string) *SVGIMAGEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
