// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T23:50:51+01:00

// package svg feColorMatrix is generated from configuration file.
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <feColorMatrix> SVG filter element changes colors based on a
// transformation matrix. Every pixel's color value (represented by an [R,G,B,A]
// vector) is matrix multiplied to create a new color.
type SVGFECOLORMATRIXElement struct {
	*Element
}

// Create a new SVGFECOLORMATRIXElement element.
// This will create a new element with the tag
// "feColorMatrix" during rendering.
func SVG_FECOLORMATRIX(children ...ElementRenderer) *SVGFECOLORMATRIXElement {
	e := NewElement("feColorMatrix", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFECOLORMATRIXElement{Element: e}
}

func (e *SVGFECOLORMATRIXElement) Children(children ...ElementRenderer) *SVGFECOLORMATRIXElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFECOLORMATRIXElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) BoolAttr(name string) *SVGFECOLORMATRIXElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFECOLORMATRIXElement) IfBoolAttr(condition bool, name string) *SVGFECOLORMATRIXElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) Attr(name, value string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFECOLORMATRIXElement) IfAttr(condition bool, name, value string) *SVGFECOLORMATRIXElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) Text(text string) *SVGFECOLORMATRIXElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFECOLORMATRIXElement) TextF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFECOLORMATRIXElement) IfText(condition bool, text string) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) IfTextF(condition bool, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) Escaped(text string) *SVGFECOLORMATRIXElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFECOLORMATRIXElement) IfEscaped(condition bool, text string) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) EscapedF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFECOLORMATRIXElement) IfEscapedF(condition bool, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) CustomData(key, value string) *SVGFECOLORMATRIXElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFECOLORMATRIXElement) IfCustomData(condition bool, key, value string) *SVGFECOLORMATRIXElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) CustomDataF(key, format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFECOLORMATRIXElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFECOLORMATRIXElement) CustomDataRemove(key string) *SVGFECOLORMATRIXElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFECOLORMATRIXElement) IN(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFECOLORMATRIXElement) INF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFECOLORMATRIXElement) IfIN(condition bool, s string) *SVGFECOLORMATRIXElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFECOLORMATRIXElement) IfINF(condition bool, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
// Remove the attribute IN from the element.
func (e *SVGFECOLORMATRIXElement) INRemove(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// The input for this filter.
func (e *SVGFECOLORMATRIXElement) INRemoveF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.INRemove(fmt.Sprintf(format, args...))
}

// The type of matrix operation.
func (e *SVGFECOLORMATRIXElement) TYPE(c SVGFeColorMatrixTypeChoice) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("type", string(c))
	return e
}

type SVGFeColorMatrixTypeChoice string

const (
	// The type of matrix operation.
	SVGFeColorMatrixType_matrix SVGFeColorMatrixTypeChoice = "matrix"
	// The type of matrix operation.
	SVGFeColorMatrixType_saturate SVGFeColorMatrixTypeChoice = "saturate"
	// The type of matrix operation.
	SVGFeColorMatrixType_hueRotate SVGFeColorMatrixTypeChoice = "hueRotate"
	// The type of matrix operation.
	SVGFeColorMatrixType_luminanceToAlpha SVGFeColorMatrixTypeChoice = "luminanceToAlpha"
)

// The type of matrix operation.
// Remove the attribute TYPE from the element.
func (e *SVGFECOLORMATRIXElement) TYPERemove(c SVGFeColorMatrixTypeChoice) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("type")
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFECOLORMATRIXElement) VALUES(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("values", s)
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFECOLORMATRIXElement) VALUESF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.VALUES(fmt.Sprintf(format, args...))
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFECOLORMATRIXElement) IfVALUES(condition bool, s string) *SVGFECOLORMATRIXElement {
	if condition {
		e.VALUES(s)
	}
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFECOLORMATRIXElement) IfVALUESF(condition bool, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.VALUES(fmt.Sprintf(format, args...))
	}
	return e
}

// The list of one or more numbers that represent the matrix.
// Remove the attribute VALUES from the element.
func (e *SVGFECOLORMATRIXElement) VALUESRemove(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("values")
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFECOLORMATRIXElement) VALUESRemoveF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.VALUESRemove(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFECOLORMATRIXElement) ID(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOLORMATRIXElement) IDF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFECOLORMATRIXElement) IfID(condition bool, s string) *SVGFECOLORMATRIXElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOLORMATRIXElement) IfIDF(condition bool, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFECOLORMATRIXElement) IDRemove(s string) *SVGFECOLORMATRIXElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOLORMATRIXElement) IDRemoveF(format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOLORMATRIXElement) CLASS(s ...string) *SVGFECOLORMATRIXElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOLORMATRIXElement) IfCLASS(condition bool, s ...string) *SVGFECOLORMATRIXElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGFECOLORMATRIXElement) CLASSRemove(s ...string) *SVGFECOLORMATRIXElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOLORMATRIXElement) STYLEF(k string, format string, args ...any) *SVGFECOLORMATRIXElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFECOLORMATRIXElement) IfSTYLE(condition bool, k string, v string) *SVGFECOLORMATRIXElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOLORMATRIXElement) STYLE(k string, v string) *SVGFECOLORMATRIXElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOLORMATRIXElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFECOLORMATRIXElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFECOLORMATRIXElement) STYLEMap(m map[string]string) *SVGFECOLORMATRIXElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFECOLORMATRIXElement) STYLERemove(keys ...string) *SVGFECOLORMATRIXElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
