// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feComponentTransfer is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feComponentTransfer> SVG filter primitive performs color-component-wise
// remapping of data for each pixel. It allows operations like brightness
// adjustment, contrast adjustment, color balance or thresholding.
type SVGFECOMPONENTTRANSFERElement struct {
	*Element
}

// Create a new SVGFECOMPONENTTRANSFERElement element.
// This will create a new element with the tag
// "feComponentTransfer" during rendering.
func SVG_FECOMPONENTTRANSFER(children ...ElementRenderer) *SVGFECOMPONENTTRANSFERElement {
	e := NewElement("feComponentTransfer", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFECOMPONENTTRANSFERElement{Element: e}
}

func (e *SVGFECOMPONENTTRANSFERElement) Children(children ...ElementRenderer) *SVGFECOMPONENTTRANSFERElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) BoolAttr(name string) *SVGFECOMPONENTTRANSFERElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfBoolAttr(condition bool, name string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) Attr(name, value string) *SVGFECOMPONENTTRANSFERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfAttr(condition bool, name, value string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) Text(text string) *SVGFECOMPONENTTRANSFERElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) TextF(format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPONENTTRANSFERElement) IfText(condition bool, text string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfTextF(condition bool, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) Escaped(text string) *SVGFECOMPONENTTRANSFERElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfEscaped(condition bool, text string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) EscapedF(format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPONENTTRANSFERElement) IfEscapedF(condition bool, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) CustomData(key, value string) *SVGFECOMPONENTTRANSFERElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) IfCustomData(condition bool, key, value string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) CustomDataF(key, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPONENTTRANSFERElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFECOMPONENTTRANSFERElement) CustomDataRemove(key string) *SVGFECOMPONENTTRANSFERElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFECOMPONENTTRANSFERElement) IN(s string) *SVGFECOMPONENTTRANSFERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFECOMPONENTTRANSFERElement) INF(format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFECOMPONENTTRANSFERElement) IfIN(condition bool, s string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFECOMPONENTTRANSFERElement) IfINF(condition bool, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
//
// Remove the attribute IN from the element.
func (e *SVGFECOMPONENTTRANSFERElement) INRemove() *SVGFECOMPONENTTRANSFERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPONENTTRANSFERElement) ID(s string) *SVGFECOMPONENTTRANSFERElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPONENTTRANSFERElement) IDF(format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFECOMPONENTTRANSFERElement) IfID(condition bool, s string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPONENTTRANSFERElement) IfIDF(condition bool, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFECOMPONENTTRANSFERElement) IDRemove() *SVGFECOMPONENTTRANSFERElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOMPONENTTRANSFERElement) CLASS(s string) *SVGFECOMPONENTTRANSFERElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOMPONENTTRANSFERElement) IfCLASS(condition bool, s string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFECOMPONENTTRANSFERElement) CLASSRemove(s ...string) *SVGFECOMPONENTTRANSFERElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) STYLEPairs(pairs ...string) *SVGFECOMPONENTTRANSFERElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) STYLE(s string) *SVGFECOMPONENTTRANSFERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) IfSTYLE(condition bool, s string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) STYLEAdd(k string, v string) *SVGFECOMPONENTTRANSFERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) STYLEAddF(k string, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPONENTTRANSFERElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFECOMPONENTTRANSFERElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFECOMPONENTTRANSFERElement) STYLEMap(m map[string]string) *SVGFECOMPONENTTRANSFERElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFECOMPONENTTRANSFERElement) STYLERemove(keys ...string) *SVGFECOMPONENTTRANSFERElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
