// Code generated by gostar generator. DO NOT EDIT.
// Source: elements/svg_fe_flood.go
// Generated: 2025-11-02T00:49:57+01:00

// package svg feFlood is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <feFlood> SVG filter primitive fills the filter subregion with the color
// and opacity defined by flood-color and flood-opacity.
type SVGFEFLOODElement struct {
	*Element
}

// Create a new SVGFEFLOODElement element.
// This will create a new element with the tag
// "feFlood" during rendering.
func SVG_FEFLOOD(children ...ElementRenderer) *SVGFEFLOODElement {
	e := NewElement("feFlood", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEFLOODElement{Element: e}
}

func (e *SVGFEFLOODElement) Children(children ...ElementRenderer) *SVGFEFLOODElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEFLOODElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEFLOODElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEFLOODElement) BoolAttr(name string) *SVGFEFLOODElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEFLOODElement) IfBoolAttr(condition bool, name string) *SVGFEFLOODElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEFLOODElement) Attr(name, value string) *SVGFEFLOODElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEFLOODElement) IfAttr(condition bool, name, value string) *SVGFEFLOODElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEFLOODElement) Text(text string) *SVGFEFLOODElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEFLOODElement) TextF(format string, args ...any) *SVGFEFLOODElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEFLOODElement) IfText(condition bool, text string) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEFLOODElement) IfTextF(condition bool, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEFLOODElement) Escaped(text string) *SVGFEFLOODElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEFLOODElement) IfEscaped(condition bool, text string) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEFLOODElement) EscapedF(format string, args ...any) *SVGFEFLOODElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEFLOODElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEFLOODElement) CustomData(key, value string) *SVGFEFLOODElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEFLOODElement) IfCustomData(condition bool, key, value string) *SVGFEFLOODElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEFLOODElement) CustomDataF(key, format string, args ...any) *SVGFEFLOODElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEFLOODElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEFLOODElement) CustomDataRemove(key string) *SVGFEFLOODElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEFLOODElement) FLOOD_COLOR(s string) *SVGFEFLOODElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("flood-color", s)
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEFLOODElement) FLOOD_COLORF(format string, args ...any) *SVGFEFLOODElement {
	return e.FLOOD_COLOR(fmt.Sprintf(format, args...))
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEFLOODElement) IfFLOOD_COLOR(condition bool, s string) *SVGFEFLOODElement {
	if condition {
		e.FLOOD_COLOR(s)
	}
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEFLOODElement) IfFLOOD_COLORF(condition bool, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.FLOOD_COLOR(fmt.Sprintf(format, args...))
	}
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
// Remove the attribute FLOOD_COLOR from the element.
func (e *SVGFEFLOODElement) FLOOD_COLORRemove(s string) *SVGFEFLOODElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("flood-color")
	return e
}

// The flood-color attribute indicates what color to use to flood the current
// filter primitive subregion defined through the <feFlood> element. If
// attribute 'flood-color' is not specified, then the effect is as if a value of
// black were specified.
func (e *SVGFEFLOODElement) FLOOD_COLORRemoveF(format string, args ...any) *SVGFEFLOODElement {
	return e.FLOOD_COLORRemove(fmt.Sprintf(format, args...))
}

// The flood-opacity attribute indicates the opacity value to use across the
// current filter primitive subregion defined through the <feFlood> element.
func (e *SVGFEFLOODElement) FLOOD_OPACITY(f float64) *SVGFEFLOODElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("flood-opacity", f)
	return e
}

// The flood-opacity attribute indicates the opacity value to use across the
// current filter primitive subregion defined through the <feFlood> element.
func (e *SVGFEFLOODElement) IfFLOOD_OPACITY(condition bool, f float64) *SVGFEFLOODElement {
	if condition {
		e.FLOOD_OPACITY(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEFLOODElement) ID(s string) *SVGFEFLOODElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEFLOODElement) IDF(format string, args ...any) *SVGFEFLOODElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEFLOODElement) IfID(condition bool, s string) *SVGFEFLOODElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEFLOODElement) IfIDF(condition bool, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFEFLOODElement) IDRemove(s string) *SVGFEFLOODElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGFEFLOODElement) IDRemoveF(format string, args ...any) *SVGFEFLOODElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEFLOODElement) CLASS(s ...string) *SVGFEFLOODElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEFLOODElement) IfCLASS(condition bool, s ...string) *SVGFEFLOODElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGFEFLOODElement) CLASSRemove(s ...string) *SVGFEFLOODElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEFLOODElement) STYLEF(k string, format string, args ...any) *SVGFEFLOODElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEFLOODElement) IfSTYLE(condition bool, k string, v string) *SVGFEFLOODElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEFLOODElement) STYLE(k string, v string) *SVGFEFLOODElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEFLOODElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFEFLOODElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFEFLOODElement) STYLEMap(m map[string]string) *SVGFEFLOODElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEFLOODElement) STYLERemove(keys ...string) *SVGFEFLOODElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
