// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg fePointLight is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <fePointLight> SVG filter primitive defines a light source at a point on
// the plane of the user coordinate system.
type SVGFEPOINTLIGHTElement struct {
	*Element
}

// Create a new SVGFEPOINTLIGHTElement element.
// This will create a new element with the tag
// "fePointLight" during rendering.
func SVG_FEPOINTLIGHT(children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	e := NewElement("fePointLight", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEPOINTLIGHTElement{Element: e}
}

func (e *SVGFEPOINTLIGHTElement) Children(children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) BoolAttr(name string) *SVGFEPOINTLIGHTElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfBoolAttr(condition bool, name string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Attr(name, value string) *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfAttr(condition bool, name, value string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Text(text string) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEPOINTLIGHTElement) TextF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfText(condition bool, text string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfTextF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) Escaped(text string) *SVGFEPOINTLIGHTElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfEscaped(condition bool, text string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) EscapedF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomData(key, value string) *SVGFEPOINTLIGHTElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEPOINTLIGHTElement) IfCustomData(condition bool, key, value string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomDataF(key, format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEPOINTLIGHTElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEPOINTLIGHTElement) CustomDataRemove(key string) *SVGFEPOINTLIGHTElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x attribute indicates the x location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) X(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

// The x attribute indicates the x location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfX(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y attribute indicates the y location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) Y(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

// The y attribute indicates the y location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfY(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The z attribute indicates the z location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) Z(f float64) *SVGFEPOINTLIGHTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("z", f)
	return e
}

// The z attribute indicates the z location of the light source in the
// coordinate system established by attribute 'primitiveUnits' on the <filter>
// element.
func (e *SVGFEPOINTLIGHTElement) IfZ(condition bool, f float64) *SVGFEPOINTLIGHTElement {
	if condition {
		e.Z(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) ID(s string) *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IDF(format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IfID(condition bool, s string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEPOINTLIGHTElement) IfIDF(condition bool, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFEPOINTLIGHTElement) IDRemove() *SVGFEPOINTLIGHTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEPOINTLIGHTElement) CLASS(s string) *SVGFEPOINTLIGHTElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEPOINTLIGHTElement) IfCLASS(condition bool, s string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFEPOINTLIGHTElement) CLASSRemove(s ...string) *SVGFEPOINTLIGHTElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLEPairs(pairs ...string) *SVGFEPOINTLIGHTElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLE(s string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) IfSTYLE(condition bool, s string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLEAdd(k string, v string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) STYLEAddF(k string, format string, args ...any) *SVGFEPOINTLIGHTElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFEPOINTLIGHTElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEPOINTLIGHTElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFEPOINTLIGHTElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFEPOINTLIGHTElement) STYLEMap(m map[string]string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEPOINTLIGHTElement) STYLERemove(keys ...string) *SVGFEPOINTLIGHTElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
