// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-03T23:53:56+01:00

// package svg animateMotion is generated from configuration file.
package elements

import (
	"fmt"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <animateMotion> SVG element is used to animate a transformation attribute
// on a target element, thereby allowing the animation of translation, rotation,
// and scaling.
type SVGANIMATEMOTIONElement struct {
	*Element
}

// Create a new SVGANIMATEMOTIONElement element.
// This will create a new element with the tag
// "animateMotion" during rendering.
func SVG_ANIMATEMOTION(children ...ElementRenderer) *SVGANIMATEMOTIONElement {
	e := NewElement("animateMotion", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGANIMATEMOTIONElement{Element: e}
}

func (e *SVGANIMATEMOTIONElement) Children(children ...ElementRenderer) *SVGANIMATEMOTIONElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGANIMATEMOTIONElement) IfChildren(condition bool, children ...ElementRenderer) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) BoolAttr(name string) *SVGANIMATEMOTIONElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGANIMATEMOTIONElement) IfBoolAttr(condition bool, name string) *SVGANIMATEMOTIONElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) Attr(name, value string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGANIMATEMOTIONElement) IfAttr(condition bool, name, value string) *SVGANIMATEMOTIONElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) Text(text string) *SVGANIMATEMOTIONElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGANIMATEMOTIONElement) TextF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGANIMATEMOTIONElement) IfText(condition bool, text string) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) IfTextF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) Escaped(text string) *SVGANIMATEMOTIONElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGANIMATEMOTIONElement) IfEscaped(condition bool, text string) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) EscapedF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGANIMATEMOTIONElement) IfEscapedF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) CustomData(key, value string) *SVGANIMATEMOTIONElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGANIMATEMOTIONElement) IfCustomData(condition bool, key, value string) *SVGANIMATEMOTIONElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) CustomDataF(key, format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGANIMATEMOTIONElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGANIMATEMOTIONElement) CustomDataRemove(key string) *SVGANIMATEMOTIONElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Controls whether or not the animation is cumulative.
func (e *SVGANIMATEMOTIONElement) ACCUMULATE(c SVGAnimateMotionAccumulateChoice) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("accumulate", string(c))
	return e
}

type SVGAnimateMotionAccumulateChoice string

const (
	// The animation is not cumulative. Each iteration starts over from the
	// beginning.
	SVGAnimateMotionAccumulate_none SVGAnimateMotionAccumulateChoice = "none"
	// The animation is cumulative. Each iteration the animation picks up where it
	// left off in the previous iteration.
	SVGAnimateMotionAccumulate_sum SVGAnimateMotionAccumulateChoice = "sum"
)

// Controls whether or not the animation is cumulative.
// Remove the attribute ACCUMULATE from the element.
func (e *SVGANIMATEMOTIONElement) ACCUMULATERemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("accumulate")
	return e
}

// Controls whether or not the animation is additive.
func (e *SVGANIMATEMOTIONElement) ADDITIVE(c SVGAnimateMotionAdditiveChoice) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("additive", string(c))
	return e
}

type SVGAnimateMotionAdditiveChoice string

const (
	// The animation is not additive. The animation replaces the underlying value.
	SVGAnimateMotionAdditive_replace SVGAnimateMotionAdditiveChoice = "replace"
	// The animation is additive. The animation adds to the underlying value.
	SVGAnimateMotionAdditive_sum SVGAnimateMotionAdditiveChoice = "sum"
)

// Controls whether or not the animation is additive.
// Remove the attribute ADDITIVE from the element.
func (e *SVGANIMATEMOTIONElement) ADDITIVERemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("additive")
	return e
}

// Defines when the animation should begin.
func (e *SVGANIMATEMOTIONElement) BEGIN(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("begin", s)
	return e
}

// Defines when the animation should begin.
func (e *SVGANIMATEMOTIONElement) BEGINF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.BEGIN(fmt.Sprintf(format, args...))
}

// Defines when the animation should begin.
func (e *SVGANIMATEMOTIONElement) IfBEGIN(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.BEGIN(s)
	}
	return e
}

// Defines when the animation should begin.
func (e *SVGANIMATEMOTIONElement) IfBEGINF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.BEGIN(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines when the animation should begin.
//
// Remove the attribute BEGIN from the element.
func (e *SVGANIMATEMOTIONElement) BEGINRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("begin")
	return e
}

// Defines a relative offset value for the animation.
func (e *SVGANIMATEMOTIONElement) BY(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("by", s)
	return e
}

// Defines a relative offset value for the animation.
func (e *SVGANIMATEMOTIONElement) BYF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.BY(fmt.Sprintf(format, args...))
}

// Defines a relative offset value for the animation.
func (e *SVGANIMATEMOTIONElement) IfBY(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.BY(s)
	}
	return e
}

// Defines a relative offset value for the animation.
func (e *SVGANIMATEMOTIONElement) IfBYF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.BY(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines a relative offset value for the animation.
//
// Remove the attribute BY from the element.
func (e *SVGANIMATEMOTIONElement) BYRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("by")
	return e
}

// Defines the pacing of the animation.
func (e *SVGANIMATEMOTIONElement) CALC_MODE(c SVGAnimateMotionCalcModeChoice) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("calcMode", string(c))
	return e
}

type SVGAnimateMotionCalcModeChoice string

const (
	// The animation is not paced. Each iteration of the animation is displayed as
	// fast as possible.
	SVGAnimateMotionCalcMode_discrete SVGAnimateMotionCalcModeChoice = "discrete"
	// The animation is paced such that it takes the same amount of time to go from
	// the start value to the end value throughout the animation.
	SVGAnimateMotionCalcMode_linear SVGAnimateMotionCalcModeChoice = "linear"
	// The animation is paced according to a cubic function.
	SVGAnimateMotionCalcMode_paced SVGAnimateMotionCalcModeChoice = "paced"
	// The animation is paced according to a cubic function, but with easing at both
	// the start and end.
	SVGAnimateMotionCalcMode_spline SVGAnimateMotionCalcModeChoice = "spline"
)

// Defines the pacing of the animation.
// Remove the attribute CALC_MODE from the element.
func (e *SVGANIMATEMOTIONElement) CALC_MODERemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("calcMode")
	return e
}

// Defines the duration of the animation.
func (e *SVGANIMATEMOTIONElement) DUR(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dur", s)
	return e
}

// Defines the duration of the animation.
func (e *SVGANIMATEMOTIONElement) DURF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.DUR(fmt.Sprintf(format, args...))
}

// Defines the duration of the animation.
func (e *SVGANIMATEMOTIONElement) IfDUR(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.DUR(s)
	}
	return e
}

// Defines the duration of the animation.
func (e *SVGANIMATEMOTIONElement) IfDURF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.DUR(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the duration of the animation.
//
// Remove the attribute DUR from the element.
func (e *SVGANIMATEMOTIONElement) DURRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dur")
	return e
}

// Defines when the animation should end.
func (e *SVGANIMATEMOTIONElement) END(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("end", s)
	return e
}

// Defines when the animation should end.
func (e *SVGANIMATEMOTIONElement) ENDF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.END(fmt.Sprintf(format, args...))
}

// Defines when the animation should end.
func (e *SVGANIMATEMOTIONElement) IfEND(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.END(s)
	}
	return e
}

// Defines when the animation should end.
func (e *SVGANIMATEMOTIONElement) IfENDF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.END(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines when the animation should end.
//
// Remove the attribute END from the element.
func (e *SVGANIMATEMOTIONElement) ENDRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("end")
	return e
}

// Defines the fill behavior for the animation.
func (e *SVGANIMATEMOTIONElement) FILL(c SVGAnimateMotionFillChoice) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("fill", string(c))
	return e
}

type SVGAnimateMotionFillChoice string

const (
	// The animation will hold the attribute value when the animation ends.
	SVGAnimateMotionFill_freeze SVGAnimateMotionFillChoice = "freeze"
	// The animation will remove the attribute value when the animation ends.
	SVGAnimateMotionFill_remove SVGAnimateMotionFillChoice = "remove"
)

// Defines the fill behavior for the animation.
// Remove the attribute FILL from the element.
func (e *SVGANIMATEMOTIONElement) FILLRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("fill")
	return e
}

// Defines the initial value of the attribute.
func (e *SVGANIMATEMOTIONElement) FROM(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("from", s)
	return e
}

// Defines the initial value of the attribute.
func (e *SVGANIMATEMOTIONElement) FROMF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.FROM(fmt.Sprintf(format, args...))
}

// Defines the initial value of the attribute.
func (e *SVGANIMATEMOTIONElement) IfFROM(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.FROM(s)
	}
	return e
}

// Defines the initial value of the attribute.
func (e *SVGANIMATEMOTIONElement) IfFROMF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.FROM(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the initial value of the attribute.
//
// Remove the attribute FROM from the element.
func (e *SVGANIMATEMOTIONElement) FROMRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("from")
	return e
}

// Defines the values for a cubic Bézier function that controls interval
// pacing.
func (e *SVGANIMATEMOTIONElement) KEY_SPLINES(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("keySplines", s)
	return e
}

// Defines the values for a cubic Bézier function that controls interval
// pacing.
func (e *SVGANIMATEMOTIONElement) KEY_SPLINESF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.KEY_SPLINES(fmt.Sprintf(format, args...))
}

// Defines the values for a cubic Bézier function that controls interval
// pacing.
func (e *SVGANIMATEMOTIONElement) IfKEY_SPLINES(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.KEY_SPLINES(s)
	}
	return e
}

// Defines the values for a cubic Bézier function that controls interval
// pacing.
func (e *SVGANIMATEMOTIONElement) IfKEY_SPLINESF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.KEY_SPLINES(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the values for a cubic Bézier function that controls interval
// pacing.
//
// Remove the attribute KEY_SPLINES from the element.
func (e *SVGANIMATEMOTIONElement) KEY_SPLINESRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("keySplines")
	return e
}

// Defines when the animation should take place in terms of time fractions.
func (e *SVGANIMATEMOTIONElement) KEY_TIMES(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("keyTimes", s)
	return e
}

// Defines when the animation should take place in terms of time fractions.
func (e *SVGANIMATEMOTIONElement) KEY_TIMESF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.KEY_TIMES(fmt.Sprintf(format, args...))
}

// Defines when the animation should take place in terms of time fractions.
func (e *SVGANIMATEMOTIONElement) IfKEY_TIMES(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.KEY_TIMES(s)
	}
	return e
}

// Defines when the animation should take place in terms of time fractions.
func (e *SVGANIMATEMOTIONElement) IfKEY_TIMESF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.KEY_TIMES(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines when the animation should take place in terms of time fractions.
//
// Remove the attribute KEY_TIMES from the element.
func (e *SVGANIMATEMOTIONElement) KEY_TIMESRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("keyTimes")
	return e
}

// Defines the maximum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) MAX(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("max", s)
	return e
}

// Defines the maximum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) MAXF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.MAX(fmt.Sprintf(format, args...))
}

// Defines the maximum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) IfMAX(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.MAX(s)
	}
	return e
}

// Defines the maximum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) IfMAXF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.MAX(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the maximum value allowed for the attribute.
//
// Remove the attribute MAX from the element.
func (e *SVGANIMATEMOTIONElement) MAXRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("max")
	return e
}

// Defines the minimum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) MIN(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("min", s)
	return e
}

// Defines the minimum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) MINF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.MIN(fmt.Sprintf(format, args...))
}

// Defines the minimum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) IfMIN(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.MIN(s)
	}
	return e
}

// Defines the minimum value allowed for the attribute.
func (e *SVGANIMATEMOTIONElement) IfMINF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.MIN(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the minimum value allowed for the attribute.
//
// Remove the attribute MIN from the element.
func (e *SVGANIMATEMOTIONElement) MINRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("min")
	return e
}

// Defines the number of times the animation should repeat.
func (e *SVGANIMATEMOTIONElement) REPEAT_COUNT(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("repeatCount", s)
	return e
}

// Defines the number of times the animation should repeat.
func (e *SVGANIMATEMOTIONElement) REPEAT_COUNTF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.REPEAT_COUNT(fmt.Sprintf(format, args...))
}

// Defines the number of times the animation should repeat.
func (e *SVGANIMATEMOTIONElement) IfREPEAT_COUNT(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.REPEAT_COUNT(s)
	}
	return e
}

// Defines the number of times the animation should repeat.
func (e *SVGANIMATEMOTIONElement) IfREPEAT_COUNTF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.REPEAT_COUNT(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the number of times the animation should repeat.
//
// Remove the attribute REPEAT_COUNT from the element.
func (e *SVGANIMATEMOTIONElement) REPEAT_COUNTRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("repeatCount")
	return e
}

// Defines the duration for repeating an animation.
func (e *SVGANIMATEMOTIONElement) REPEAT_DUR(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("repeatDur", s)
	return e
}

// Defines the duration for repeating an animation.
func (e *SVGANIMATEMOTIONElement) REPEAT_DURF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.REPEAT_DUR(fmt.Sprintf(format, args...))
}

// Defines the duration for repeating an animation.
func (e *SVGANIMATEMOTIONElement) IfREPEAT_DUR(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.REPEAT_DUR(s)
	}
	return e
}

// Defines the duration for repeating an animation.
func (e *SVGANIMATEMOTIONElement) IfREPEAT_DURF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.REPEAT_DUR(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the duration for repeating an animation.
//
// Remove the attribute REPEAT_DUR from the element.
func (e *SVGANIMATEMOTIONElement) REPEAT_DURRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("repeatDur")
	return e
}

// Defines if an animation should restart after it completes.
func (e *SVGANIMATEMOTIONElement) RESTART(c SVGAnimateMotionRestartChoice) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("restart", string(c))
	return e
}

type SVGAnimateMotionRestartChoice string

const (
	// The animation will restart indefinitely.
	SVGAnimateMotionRestart_always SVGAnimateMotionRestartChoice = "always"
	// The animation will not restart after it completes.
	SVGAnimateMotionRestart_never SVGAnimateMotionRestartChoice = "never"
	// The animation will restart after it completes if the animation is not
	// currently active.
	SVGAnimateMotionRestart_whenNotActive SVGAnimateMotionRestartChoice = "whenNotActive"
)

// Defines if an animation should restart after it completes.
// Remove the attribute RESTART from the element.
func (e *SVGANIMATEMOTIONElement) RESTARTRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("restart")
	return e
}

// Defines the ending value of the attribute.
func (e *SVGANIMATEMOTIONElement) TO(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("to", s)
	return e
}

// Defines the ending value of the attribute.
func (e *SVGANIMATEMOTIONElement) TOF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.TO(fmt.Sprintf(format, args...))
}

// Defines the ending value of the attribute.
func (e *SVGANIMATEMOTIONElement) IfTO(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.TO(s)
	}
	return e
}

// Defines the ending value of the attribute.
func (e *SVGANIMATEMOTIONElement) IfTOF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.TO(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the ending value of the attribute.
//
// Remove the attribute TO from the element.
func (e *SVGANIMATEMOTIONElement) TORemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("to")
	return e
}

// Defines a list of discrete values to interpolate.
func (e *SVGANIMATEMOTIONElement) VALUES(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("values", s)
	return e
}

// Defines a list of discrete values to interpolate.
func (e *SVGANIMATEMOTIONElement) VALUESF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.VALUES(fmt.Sprintf(format, args...))
}

// Defines a list of discrete values to interpolate.
func (e *SVGANIMATEMOTIONElement) IfVALUES(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.VALUES(s)
	}
	return e
}

// Defines a list of discrete values to interpolate.
func (e *SVGANIMATEMOTIONElement) IfVALUESF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.VALUES(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines a list of discrete values to interpolate.
//
// Remove the attribute VALUES from the element.
func (e *SVGANIMATEMOTIONElement) VALUESRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("values")
	return e
}

// Specifies a unique id for an element
func (e *SVGANIMATEMOTIONElement) ID(s string) *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGANIMATEMOTIONElement) IDF(format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGANIMATEMOTIONElement) IfID(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGANIMATEMOTIONElement) IfIDF(condition bool, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGANIMATEMOTIONElement) IDRemove() *SVGANIMATEMOTIONElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGANIMATEMOTIONElement) CLASS(s string) *SVGANIMATEMOTIONElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGANIMATEMOTIONElement) IfCLASS(condition bool, s string) *SVGANIMATEMOTIONElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGANIMATEMOTIONElement) CLASSRemove(s ...string) *SVGANIMATEMOTIONElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGANIMATEMOTIONElement) STYLEF(k string, format string, args ...any) *SVGANIMATEMOTIONElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGANIMATEMOTIONElement) IfSTYLE(condition bool, k string, v string) *SVGANIMATEMOTIONElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGANIMATEMOTIONElement) STYLE(k string, v string) *SVGANIMATEMOTIONElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGANIMATEMOTIONElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGANIMATEMOTIONElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGANIMATEMOTIONElement) STYLEMap(m map[string]string) *SVGANIMATEMOTIONElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGANIMATEMOTIONElement) STYLERemove(keys ...string) *SVGANIMATEMOTIONElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
