// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T15:01:36+01:00

// package svg title is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <title> SVG element represents a text container used for the context
// information. This element is usually nested inside a <desc> element.
type SVGTITLEElement struct {
	*Element
}

// Create a new SVGTITLEElement element.
// This will create a new element with the tag
// "title" during rendering.
func SVG_TITLE(children ...ElementRenderer) *SVGTITLEElement {
	e := NewElement("title", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGTITLEElement{Element: e}
}

func (e *SVGTITLEElement) Children(children ...ElementRenderer) *SVGTITLEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGTITLEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGTITLEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGTITLEElement) BoolAttr(name string) *SVGTITLEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGTITLEElement) IfBoolAttr(condition bool, name string) *SVGTITLEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGTITLEElement) Attr(name, value string) *SVGTITLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGTITLEElement) IfAttr(condition bool, name, value string) *SVGTITLEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGTITLEElement) Text(text string) *SVGTITLEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGTITLEElement) TextF(format string, args ...any) *SVGTITLEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGTITLEElement) IfText(condition bool, text string) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGTITLEElement) IfTextF(condition bool, format string, args ...any) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGTITLEElement) Escaped(text string) *SVGTITLEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGTITLEElement) IfEscaped(condition bool, text string) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGTITLEElement) EscapedF(format string, args ...any) *SVGTITLEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGTITLEElement) IfEscapedF(condition bool, format string, args ...any) *SVGTITLEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGTITLEElement) CustomData(key, value string) *SVGTITLEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGTITLEElement) IfCustomData(condition bool, key, value string) *SVGTITLEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGTITLEElement) CustomDataF(key, format string, args ...any) *SVGTITLEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGTITLEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGTITLEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGTITLEElement) CustomDataRemove(key string) *SVGTITLEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Specifies a unique id for an element
func (e *SVGTITLEElement) ID(s string) *SVGTITLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGTITLEElement) IDF(format string, args ...any) *SVGTITLEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGTITLEElement) IfID(condition bool, s string) *SVGTITLEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGTITLEElement) IfIDF(condition bool, format string, args ...any) *SVGTITLEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGTITLEElement) IDRemove(s string) *SVGTITLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGTITLEElement) IDRemoveF(format string, args ...any) *SVGTITLEElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGTITLEElement) CLASS(s ...string) *SVGTITLEElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGTITLEElement) IfCLASS(condition bool, s ...string) *SVGTITLEElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGTITLEElement) CLASSRemove(s ...string) *SVGTITLEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTITLEElement) STYLEF(k string, format string, args ...any) *SVGTITLEElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGTITLEElement) IfSTYLE(condition bool, k string, v string) *SVGTITLEElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTITLEElement) STYLE(k string, v string) *SVGTITLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGTITLEElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGTITLEElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGTITLEElement) STYLEMap(m map[string]string) *SVGTITLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGTITLEElement) STYLERemove(keys ...string) *SVGTITLEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
