// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-03T23:53:57+01:00

// package svg feDiffuseLighting is generated from configuration file.
package elements

import (
	"fmt"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feDiffuseLighting> SVG filter primitive lights an image using the alpha
// channel as a bump map. The resulting image, which is an RGBA opaque image,
// depends on the light color, light position and surface geometry of the input
// bump map.
type SVGFEDIFFUSELIGHTINGElement struct {
	*Element
}

// Create a new SVGFEDIFFUSELIGHTINGElement element.
// This will create a new element with the tag
// "feDiffuseLighting" during rendering.
func SVG_FEDIFFUSELIGHTING(children ...ElementRenderer) *SVGFEDIFFUSELIGHTINGElement {
	e := NewElement("feDiffuseLighting", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEDIFFUSELIGHTINGElement{Element: e}
}

func (e *SVGFEDIFFUSELIGHTINGElement) Children(children ...ElementRenderer) *SVGFEDIFFUSELIGHTINGElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) BoolAttr(name string) *SVGFEDIFFUSELIGHTINGElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfBoolAttr(condition bool, name string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) Attr(name, value string) *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfAttr(condition bool, name, value string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) Text(text string) *SVGFEDIFFUSELIGHTINGElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) TextF(format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfText(condition bool, text string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfTextF(condition bool, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) Escaped(text string) *SVGFEDIFFUSELIGHTINGElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfEscaped(condition bool, text string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) EscapedF(format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) CustomData(key, value string) *SVGFEDIFFUSELIGHTINGElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfCustomData(condition bool, key, value string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) CustomDataF(key, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEDIFFUSELIGHTINGElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEDIFFUSELIGHTINGElement) CustomDataRemove(key string) *SVGFEDIFFUSELIGHTINGElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFEDIFFUSELIGHTINGElement) IN(s string) *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFEDIFFUSELIGHTINGElement) INF(format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFEDIFFUSELIGHTINGElement) IfIN(condition bool, s string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFEDIFFUSELIGHTINGElement) IfINF(condition bool, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
//
// Remove the attribute IN from the element.
func (e *SVGFEDIFFUSELIGHTINGElement) INRemove() *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// The 'surfaceScale' attribute indicates the height of the surface when the
// alpha channel is 1.0.
func (e *SVGFEDIFFUSELIGHTINGElement) SURFACE_SCALE(f float64) *SVGFEDIFFUSELIGHTINGElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("surfaceScale", f)
	return e
}

// The 'surfaceScale' attribute indicates the height of the surface when the
// alpha channel is 1.0.
func (e *SVGFEDIFFUSELIGHTINGElement) IfSURFACE_SCALE(condition bool, f float64) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.SURFACE_SCALE(f)
	}
	return e
}

// The diffuseConstant attribute represents the proportion of the light that is
// reflected by the surface.
func (e *SVGFEDIFFUSELIGHTINGElement) DIFFUSE_CONSTANT(f float64) *SVGFEDIFFUSELIGHTINGElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("diffuseConstant", f)
	return e
}

// The diffuseConstant attribute represents the proportion of the light that is
// reflected by the surface.
func (e *SVGFEDIFFUSELIGHTINGElement) IfDIFFUSE_CONSTANT(condition bool, f float64) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.DIFFUSE_CONSTANT(f)
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFEDIFFUSELIGHTINGElement) KERNEL_UNIT_LENGTH(s string) *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("kernelUnitLength", s)
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFEDIFFUSELIGHTINGElement) KERNEL_UNIT_LENGTHF(format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.KERNEL_UNIT_LENGTH(fmt.Sprintf(format, args...))
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFEDIFFUSELIGHTINGElement) IfKERNEL_UNIT_LENGTH(condition bool, s string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.KERNEL_UNIT_LENGTH(s)
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFEDIFFUSELIGHTINGElement) IfKERNEL_UNIT_LENGTHF(condition bool, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.KERNEL_UNIT_LENGTH(fmt.Sprintf(format, args...))
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
//
// Remove the attribute KERNEL_UNIT_LENGTH from the element.
func (e *SVGFEDIFFUSELIGHTINGElement) KERNEL_UNIT_LENGTHRemove() *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("kernelUnitLength")
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDIFFUSELIGHTINGElement) ID(s string) *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDIFFUSELIGHTINGElement) IDF(format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEDIFFUSELIGHTINGElement) IfID(condition bool, s string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEDIFFUSELIGHTINGElement) IfIDF(condition bool, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFEDIFFUSELIGHTINGElement) IDRemove() *SVGFEDIFFUSELIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEDIFFUSELIGHTINGElement) CLASS(s string) *SVGFEDIFFUSELIGHTINGElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEDIFFUSELIGHTINGElement) IfCLASS(condition bool, s string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFEDIFFUSELIGHTINGElement) CLASSRemove(s ...string) *SVGFEDIFFUSELIGHTINGElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDIFFUSELIGHTINGElement) STYLEF(k string, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEDIFFUSELIGHTINGElement) IfSTYLE(condition bool, k string, v string) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDIFFUSELIGHTINGElement) STYLE(k string, v string) *SVGFEDIFFUSELIGHTINGElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEDIFFUSELIGHTINGElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGFEDIFFUSELIGHTINGElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFEDIFFUSELIGHTINGElement) STYLEMap(m map[string]string) *SVGFEDIFFUSELIGHTINGElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEDIFFUSELIGHTINGElement) STYLERemove(keys ...string) *SVGFEDIFFUSELIGHTINGElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
