// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feSpecularLighting is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feSpecularLighting> SVG filter primitive lights a source graphic using
// the alpha channel as a bump map. The resulting image is an RGBA image based
// on the light color. The lighting calculation follows the standard specular
// component of the Phong lighting model. The resulting image depends on the
// light color, light position and surface geometry of the input bump map.
type SVGFESPECULARLIGHTINGElement struct {
	*Element
}

// Create a new SVGFESPECULARLIGHTINGElement element.
// This will create a new element with the tag
// "feSpecularLighting" during rendering.
func SVG_FESPECULARLIGHTING(children ...ElementRenderer) *SVGFESPECULARLIGHTINGElement {
	e := NewElement("feSpecularLighting", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFESPECULARLIGHTINGElement{Element: e}
}

func (e *SVGFESPECULARLIGHTINGElement) Children(children ...ElementRenderer) *SVGFESPECULARLIGHTINGElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) BoolAttr(name string) *SVGFESPECULARLIGHTINGElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfBoolAttr(condition bool, name string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) Attr(name, value string) *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfAttr(condition bool, name, value string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) Text(text string) *SVGFESPECULARLIGHTINGElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) TextF(format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFESPECULARLIGHTINGElement) IfText(condition bool, text string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfTextF(condition bool, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) Escaped(text string) *SVGFESPECULARLIGHTINGElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfEscaped(condition bool, text string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) EscapedF(format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFESPECULARLIGHTINGElement) IfEscapedF(condition bool, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) CustomData(key, value string) *SVGFESPECULARLIGHTINGElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) IfCustomData(condition bool, key, value string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) CustomDataF(key, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFESPECULARLIGHTINGElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFESPECULARLIGHTINGElement) CustomDataRemove(key string) *SVGFESPECULARLIGHTINGElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFESPECULARLIGHTINGElement) IN(s string) *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFESPECULARLIGHTINGElement) INF(format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFESPECULARLIGHTINGElement) IfIN(condition bool, s string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFESPECULARLIGHTINGElement) IfINF(condition bool, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
//
// Remove the attribute IN from the element.
func (e *SVGFESPECULARLIGHTINGElement) INRemove() *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// The 'surfaceScale' attribute indicates the height of the surface when the
// alpha channel is 1.0.
func (e *SVGFESPECULARLIGHTINGElement) SURFACE_SCALE(f float64) *SVGFESPECULARLIGHTINGElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("surfaceScale", f)
	return e
}

// The 'surfaceScale' attribute indicates the height of the surface when the
// alpha channel is 1.0.
func (e *SVGFESPECULARLIGHTINGElement) IfSURFACE_SCALE(condition bool, f float64) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.SURFACE_SCALE(f)
	}
	return e
}

// The specularConstant attribute represents the diffuse reflection constant.
func (e *SVGFESPECULARLIGHTINGElement) SPECULAR_CONSTANT(f float64) *SVGFESPECULARLIGHTINGElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("specularConstant", f)
	return e
}

// The specularConstant attribute represents the diffuse reflection constant.
func (e *SVGFESPECULARLIGHTINGElement) IfSPECULAR_CONSTANT(condition bool, f float64) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.SPECULAR_CONSTANT(f)
	}
	return e
}

// The specularExponent attribute represents the specular reflection constant.
func (e *SVGFESPECULARLIGHTINGElement) SPECULAR_EXPONENT(f float64) *SVGFESPECULARLIGHTINGElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("specularExponent", f)
	return e
}

// The specularExponent attribute represents the specular reflection constant.
func (e *SVGFESPECULARLIGHTINGElement) IfSPECULAR_EXPONENT(condition bool, f float64) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.SPECULAR_EXPONENT(f)
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFESPECULARLIGHTINGElement) KERNEL_UNIT_LENGTH(s string) *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("kernelUnitLength", s)
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFESPECULARLIGHTINGElement) KERNEL_UNIT_LENGTHF(format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.KERNEL_UNIT_LENGTH(fmt.Sprintf(format, args...))
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFESPECULARLIGHTINGElement) IfKERNEL_UNIT_LENGTH(condition bool, s string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.KERNEL_UNIT_LENGTH(s)
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
func (e *SVGFESPECULARLIGHTINGElement) IfKERNEL_UNIT_LENGTHF(condition bool, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.KERNEL_UNIT_LENGTH(fmt.Sprintf(format, args...))
	}
	return e
}

// The kernelUnitLength attribute defines the intended distance in current
// filter units (i.e., units as determined by the value of attribute
// 'primitiveUnits') for dx and dy in the surface normal calculation formulas.
//
// Remove the attribute KERNEL_UNIT_LENGTH from the element.
func (e *SVGFESPECULARLIGHTINGElement) KERNEL_UNIT_LENGTHRemove() *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("kernelUnitLength")
	return e
}

// Specifies a unique id for an element
func (e *SVGFESPECULARLIGHTINGElement) ID(s string) *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFESPECULARLIGHTINGElement) IDF(format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFESPECULARLIGHTINGElement) IfID(condition bool, s string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFESPECULARLIGHTINGElement) IfIDF(condition bool, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFESPECULARLIGHTINGElement) IDRemove() *SVGFESPECULARLIGHTINGElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFESPECULARLIGHTINGElement) CLASS(s string) *SVGFESPECULARLIGHTINGElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFESPECULARLIGHTINGElement) IfCLASS(condition bool, s string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFESPECULARLIGHTINGElement) CLASSRemove(s ...string) *SVGFESPECULARLIGHTINGElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) STYLEPairs(pairs ...string) *SVGFESPECULARLIGHTINGElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) STYLE(s string) *SVGFESPECULARLIGHTINGElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) IfSTYLE(condition bool, s string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) STYLEAdd(k string, v string) *SVGFESPECULARLIGHTINGElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) STYLEAddF(k string, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFESPECULARLIGHTINGElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFESPECULARLIGHTINGElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFESPECULARLIGHTINGElement) STYLEMap(m map[string]string) *SVGFESPECULARLIGHTINGElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFESPECULARLIGHTINGElement) STYLERemove(keys ...string) *SVGFESPECULARLIGHTINGElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
