// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T15:01:36+01:00

// package svg rect is generated from configuration file.
// Description:
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <rect> SVG element is a basic SVG shape that draws rectangles, defined by
// their position, width, and height. The shape is created by connecting a line
// from one point to the other three points.
type SVGRECTElement struct {
	*Element
}

// Create a new SVGRECTElement element.
// This will create a new element with the tag
// "rect" during rendering.
func SVG_RECT(children ...ElementRenderer) *SVGRECTElement {
	e := NewElement("rect", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGRECTElement{Element: e}
}

func (e *SVGRECTElement) Children(children ...ElementRenderer) *SVGRECTElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGRECTElement) IfChildren(condition bool, children ...ElementRenderer) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGRECTElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGRECTElement) BoolAttr(name string) *SVGRECTElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGRECTElement) IfBoolAttr(condition bool, name string) *SVGRECTElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGRECTElement) Attr(name, value string) *SVGRECTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGRECTElement) IfAttr(condition bool, name, value string) *SVGRECTElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGRECTElement) Text(text string) *SVGRECTElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGRECTElement) TextF(format string, args ...any) *SVGRECTElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGRECTElement) IfText(condition bool, text string) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGRECTElement) IfTextF(condition bool, format string, args ...any) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGRECTElement) Escaped(text string) *SVGRECTElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGRECTElement) IfEscaped(condition bool, text string) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGRECTElement) EscapedF(format string, args ...any) *SVGRECTElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGRECTElement) IfEscapedF(condition bool, format string, args ...any) *SVGRECTElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGRECTElement) CustomData(key, value string) *SVGRECTElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGRECTElement) IfCustomData(condition bool, key, value string) *SVGRECTElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGRECTElement) CustomDataF(key, format string, args ...any) *SVGRECTElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGRECTElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGRECTElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGRECTElement) CustomDataRemove(key string) *SVGRECTElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x-axis coordinate of the side of the rectangle which has the smaller
// x-axis value.
func (e *SVGRECTElement) X(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x", f)
	return e
}

// The x-axis coordinate of the side of the rectangle which has the smaller
// x-axis value.
func (e *SVGRECTElement) IfX(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.X(f)
	}
	return e
}

// The y-axis coordinate of the side of the rectangle which has the smaller
// y-axis value.
func (e *SVGRECTElement) Y(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y", f)
	return e
}

// The y-axis coordinate of the side of the rectangle which has the smaller
// y-axis value.
func (e *SVGRECTElement) IfY(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.Y(f)
	}
	return e
}

// The width of the rectangle.
func (e *SVGRECTElement) WIDTH(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("width", f)
	return e
}

// The width of the rectangle.
func (e *SVGRECTElement) IfWIDTH(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.WIDTH(f)
	}
	return e
}

// The height of the rectangle.
func (e *SVGRECTElement) HEIGHT(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("height", f)
	return e
}

// The height of the rectangle.
func (e *SVGRECTElement) IfHEIGHT(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.HEIGHT(f)
	}
	return e
}

// The x-axis radius of the ellipse used to round off the corners of the
// rectangle.
func (e *SVGRECTElement) RX(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("rx", f)
	return e
}

// The x-axis radius of the ellipse used to round off the corners of the
// rectangle.
func (e *SVGRECTElement) IfRX(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.RX(f)
	}
	return e
}

// The y-axis radius of the ellipse used to round off the corners of the
// rectangle.
func (e *SVGRECTElement) RY(f float64) *SVGRECTElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("ry", f)
	return e
}

// The y-axis radius of the ellipse used to round off the corners of the
// rectangle.
func (e *SVGRECTElement) IfRY(condition bool, f float64) *SVGRECTElement {
	if condition {
		e.RY(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGRECTElement) ID(s string) *SVGRECTElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGRECTElement) IDF(format string, args ...any) *SVGRECTElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGRECTElement) IfID(condition bool, s string) *SVGRECTElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGRECTElement) IfIDF(condition bool, format string, args ...any) *SVGRECTElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGRECTElement) IDRemove(s string) *SVGRECTElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGRECTElement) IDRemoveF(format string, args ...any) *SVGRECTElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGRECTElement) CLASS(s ...string) *SVGRECTElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGRECTElement) IfCLASS(condition bool, s ...string) *SVGRECTElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGRECTElement) CLASSRemove(s ...string) *SVGRECTElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRECTElement) STYLEF(k string, format string, args ...any) *SVGRECTElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGRECTElement) IfSTYLE(condition bool, k string, v string) *SVGRECTElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRECTElement) STYLE(k string, v string) *SVGRECTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGRECTElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGRECTElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGRECTElement) STYLEMap(m map[string]string) *SVGRECTElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGRECTElement) STYLERemove(keys ...string) *SVGRECTElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
