// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg clipPath is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <clipPath> SVG element defines a clipping path. A clipping path is
// used/referenced using the clip-path property.
type SVGCLIPPATHElement struct {
	*Element
}

// Create a new SVGCLIPPATHElement element.
// This will create a new element with the tag
// "clipPath" during rendering.
func SVG_CLIPPATH(children ...ElementRenderer) *SVGCLIPPATHElement {
	e := NewElement("clipPath", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGCLIPPATHElement{Element: e}
}

func (e *SVGCLIPPATHElement) Children(children ...ElementRenderer) *SVGCLIPPATHElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGCLIPPATHElement) IfChildren(condition bool, children ...ElementRenderer) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGCLIPPATHElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGCLIPPATHElement) BoolAttr(name string) *SVGCLIPPATHElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGCLIPPATHElement) IfBoolAttr(condition bool, name string) *SVGCLIPPATHElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGCLIPPATHElement) Attr(name, value string) *SVGCLIPPATHElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGCLIPPATHElement) IfAttr(condition bool, name, value string) *SVGCLIPPATHElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGCLIPPATHElement) Text(text string) *SVGCLIPPATHElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGCLIPPATHElement) TextF(format string, args ...any) *SVGCLIPPATHElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGCLIPPATHElement) IfText(condition bool, text string) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGCLIPPATHElement) IfTextF(condition bool, format string, args ...any) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGCLIPPATHElement) Escaped(text string) *SVGCLIPPATHElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGCLIPPATHElement) IfEscaped(condition bool, text string) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGCLIPPATHElement) EscapedF(format string, args ...any) *SVGCLIPPATHElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGCLIPPATHElement) IfEscapedF(condition bool, format string, args ...any) *SVGCLIPPATHElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGCLIPPATHElement) CustomData(key, value string) *SVGCLIPPATHElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGCLIPPATHElement) IfCustomData(condition bool, key, value string) *SVGCLIPPATHElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGCLIPPATHElement) CustomDataF(key, format string, args ...any) *SVGCLIPPATHElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGCLIPPATHElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGCLIPPATHElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGCLIPPATHElement) CustomDataRemove(key string) *SVGCLIPPATHElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The coordinate system for the contents of the <clipPath> element.
func (e *SVGCLIPPATHElement) CLIP_PATH_UNITS(c SVGClipPathClipPathUnitsChoice) *SVGCLIPPATHElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("clipPathUnits", string(c))
	return e
}

type SVGClipPathClipPathUnitsChoice string

const (
	// The contents of the <clipPath> element represent values in the current user
	// coordinate system.
	SVGClipPathClipPathUnits_userSpaceOnUse SVGClipPathClipPathUnitsChoice = "userSpaceOnUse"
	// The contents of the <clipPath> element represent values in the coordinate
	// system that results from taking the current user coordinate system in place
	// at the time when the <clipPath> element is referenced (i.e., the user
	// coordinate system for the element referencing the <clipPath> element via a
	// clip-path property).
	SVGClipPathClipPathUnits_objectBoundingBox SVGClipPathClipPathUnitsChoice = "objectBoundingBox"
)

// The coordinate system for the contents of the <clipPath> element.
// Remove the attribute CLIP_PATH_UNITS from the element.
func (e *SVGCLIPPATHElement) CLIP_PATH_UNITSRemove() *SVGCLIPPATHElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("clipPathUnits")
	return e
}

// Specifies a unique id for an element
func (e *SVGCLIPPATHElement) ID(s string) *SVGCLIPPATHElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGCLIPPATHElement) IDF(format string, args ...any) *SVGCLIPPATHElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGCLIPPATHElement) IfID(condition bool, s string) *SVGCLIPPATHElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGCLIPPATHElement) IfIDF(condition bool, format string, args ...any) *SVGCLIPPATHElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGCLIPPATHElement) IDRemove() *SVGCLIPPATHElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGCLIPPATHElement) CLASS(s string) *SVGCLIPPATHElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGCLIPPATHElement) IfCLASS(condition bool, s string) *SVGCLIPPATHElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGCLIPPATHElement) CLASSRemove(s ...string) *SVGCLIPPATHElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) STYLEPairs(pairs ...string) *SVGCLIPPATHElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) STYLE(s string) *SVGCLIPPATHElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) IfSTYLE(condition bool, s string) *SVGCLIPPATHElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) STYLEAdd(k string, v string) *SVGCLIPPATHElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) STYLEAddF(k string, format string, args ...any) *SVGCLIPPATHElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) IfSTYLEAdd(condition bool, k string, v string) *SVGCLIPPATHElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCLIPPATHElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGCLIPPATHElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGCLIPPATHElement) STYLEMap(m map[string]string) *SVGCLIPPATHElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGCLIPPATHElement) STYLERemove(keys ...string) *SVGCLIPPATHElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
