// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feTile is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feTile> SVG filter primitive allows to fill a target rectangle with a
// repeated, tiled pattern of an input image. The effect is similar to the one
// of a <pattern> element, but <feTile> can use complex (i.e., filter) tree as
// input, and can be animated.
type SVGFETILEElement struct {
	*Element
}

// Create a new SVGFETILEElement element.
// This will create a new element with the tag
// "feTile" during rendering.
func SVG_FETILE(children ...ElementRenderer) *SVGFETILEElement {
	e := NewElement("feTile", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFETILEElement{Element: e}
}

func (e *SVGFETILEElement) Children(children ...ElementRenderer) *SVGFETILEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFETILEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFETILEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFETILEElement) BoolAttr(name string) *SVGFETILEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFETILEElement) IfBoolAttr(condition bool, name string) *SVGFETILEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFETILEElement) Attr(name, value string) *SVGFETILEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFETILEElement) IfAttr(condition bool, name, value string) *SVGFETILEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFETILEElement) Text(text string) *SVGFETILEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFETILEElement) TextF(format string, args ...any) *SVGFETILEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFETILEElement) IfText(condition bool, text string) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFETILEElement) IfTextF(condition bool, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFETILEElement) Escaped(text string) *SVGFETILEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFETILEElement) IfEscaped(condition bool, text string) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFETILEElement) EscapedF(format string, args ...any) *SVGFETILEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFETILEElement) IfEscapedF(condition bool, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFETILEElement) CustomData(key, value string) *SVGFETILEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFETILEElement) IfCustomData(condition bool, key, value string) *SVGFETILEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFETILEElement) CustomDataF(key, format string, args ...any) *SVGFETILEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFETILEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFETILEElement) CustomDataRemove(key string) *SVGFETILEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFETILEElement) IN(s string) *SVGFETILEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFETILEElement) INF(format string, args ...any) *SVGFETILEElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFETILEElement) IfIN(condition bool, s string) *SVGFETILEElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFETILEElement) IfINF(condition bool, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
//
// Remove the attribute IN from the element.
func (e *SVGFETILEElement) INRemove() *SVGFETILEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// Specifies a unique id for an element
func (e *SVGFETILEElement) ID(s string) *SVGFETILEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFETILEElement) IDF(format string, args ...any) *SVGFETILEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFETILEElement) IfID(condition bool, s string) *SVGFETILEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFETILEElement) IfIDF(condition bool, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFETILEElement) IDRemove() *SVGFETILEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFETILEElement) CLASS(s string) *SVGFETILEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFETILEElement) IfCLASS(condition bool, s string) *SVGFETILEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFETILEElement) CLASSRemove(s ...string) *SVGFETILEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) STYLEPairs(pairs ...string) *SVGFETILEElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) STYLE(s string) *SVGFETILEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) IfSTYLE(condition bool, s string) *SVGFETILEElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) STYLEAdd(k string, v string) *SVGFETILEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) STYLEAddF(k string, format string, args ...any) *SVGFETILEElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFETILEElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFETILEElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFETILEElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFETILEElement) STYLEMap(m map[string]string) *SVGFETILEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFETILEElement) STYLERemove(keys ...string) *SVGFETILEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
