// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feGaussianBlur is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feGaussianBlur> SVG filter primitive blurs the input image by the amount
// specified in stdDeviation, which defines the bell-curve.
type SVGFEGAUSSIANBLURElement struct {
	*Element
}

// Create a new SVGFEGAUSSIANBLURElement element.
// This will create a new element with the tag
// "feGaussianBlur" during rendering.
func SVG_FEGAUSSIANBLUR(children ...ElementRenderer) *SVGFEGAUSSIANBLURElement {
	e := NewElement("feGaussianBlur", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFEGAUSSIANBLURElement{Element: e}
}

func (e *SVGFEGAUSSIANBLURElement) Children(children ...ElementRenderer) *SVGFEGAUSSIANBLURElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) BoolAttr(name string) *SVGFEGAUSSIANBLURElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfBoolAttr(condition bool, name string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) Attr(name, value string) *SVGFEGAUSSIANBLURElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfAttr(condition bool, name, value string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) Text(text string) *SVGFEGAUSSIANBLURElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFEGAUSSIANBLURElement) TextF(format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFEGAUSSIANBLURElement) IfText(condition bool, text string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfTextF(condition bool, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) Escaped(text string) *SVGFEGAUSSIANBLURElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfEscaped(condition bool, text string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) EscapedF(format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFEGAUSSIANBLURElement) IfEscapedF(condition bool, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) CustomData(key, value string) *SVGFEGAUSSIANBLURElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFEGAUSSIANBLURElement) IfCustomData(condition bool, key, value string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) CustomDataF(key, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFEGAUSSIANBLURElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFEGAUSSIANBLURElement) CustomDataRemove(key string) *SVGFEGAUSSIANBLURElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The input for this filter.
func (e *SVGFEGAUSSIANBLURElement) IN(s string) *SVGFEGAUSSIANBLURElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFEGAUSSIANBLURElement) INF(format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFEGAUSSIANBLURElement) IfIN(condition bool, s string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.IN(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFEGAUSSIANBLURElement) IfINF(condition bool, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
//
// Remove the attribute IN from the element.
func (e *SVGFEGAUSSIANBLURElement) INRemove() *SVGFEGAUSSIANBLURElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// The standard deviation for the blur operation. If two <numbers> are provided,
// the first number represents a standard deviation value along the x-axis of
// the coordinate system established by attribute 'primitiveUnits' on the
// <filter> element. The second value represents a standard deviation in Y. If
// one number is provided, then that value is used for both X and Y. Negative
// values are not allowed. A value of zero disables the effect of the given
// filter primitive (i.e., the result is a transparent black image).
func (e *SVGFEGAUSSIANBLURElement) STD_DEVIATION(f float64) *SVGFEGAUSSIANBLURElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("stdDeviation", f)
	return e
}

// The standard deviation for the blur operation. If two <numbers> are provided,
// the first number represents a standard deviation value along the x-axis of
// the coordinate system established by attribute 'primitiveUnits' on the
// <filter> element. The second value represents a standard deviation in Y. If
// one number is provided, then that value is used for both X and Y. Negative
// values are not allowed. A value of zero disables the effect of the given
// filter primitive (i.e., the result is a transparent black image).
func (e *SVGFEGAUSSIANBLURElement) IfSTD_DEVIATION(condition bool, f float64) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.STD_DEVIATION(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEGAUSSIANBLURElement) ID(s string) *SVGFEGAUSSIANBLURElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFEGAUSSIANBLURElement) IDF(format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFEGAUSSIANBLURElement) IfID(condition bool, s string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFEGAUSSIANBLURElement) IfIDF(condition bool, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFEGAUSSIANBLURElement) IDRemove() *SVGFEGAUSSIANBLURElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEGAUSSIANBLURElement) CLASS(s string) *SVGFEGAUSSIANBLURElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFEGAUSSIANBLURElement) IfCLASS(condition bool, s string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFEGAUSSIANBLURElement) CLASSRemove(s ...string) *SVGFEGAUSSIANBLURElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) STYLEPairs(pairs ...string) *SVGFEGAUSSIANBLURElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) STYLE(s string) *SVGFEGAUSSIANBLURElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) IfSTYLE(condition bool, s string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) STYLEAdd(k string, v string) *SVGFEGAUSSIANBLURElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) STYLEAddF(k string, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFEGAUSSIANBLURElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFEGAUSSIANBLURElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFEGAUSSIANBLURElement) STYLEMap(m map[string]string) *SVGFEGAUSSIANBLURElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFEGAUSSIANBLURElement) STYLERemove(keys ...string) *SVGFEGAUSSIANBLURElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
