// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-02T15:17:46+01:00

// package svg circle is generated from configuration file.
package elements

import (
	"fmt"

	"github.com/igrmk/treemap/v2"
)

// The <circle> SVG element is an SVG basic shape, used to create circles based
// on a center point and a radius.
type SVGCIRCLEElement struct {
	*Element
}

// Create a new SVGCIRCLEElement element.
// This will create a new element with the tag
// "circle" during rendering.
func SVG_CIRCLE(children ...ElementRenderer) *SVGCIRCLEElement {
	e := NewElement("circle", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGCIRCLEElement{Element: e}
}

func (e *SVGCIRCLEElement) Children(children ...ElementRenderer) *SVGCIRCLEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGCIRCLEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGCIRCLEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGCIRCLEElement) BoolAttr(name string) *SVGCIRCLEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGCIRCLEElement) IfBoolAttr(condition bool, name string) *SVGCIRCLEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGCIRCLEElement) Attr(name, value string) *SVGCIRCLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGCIRCLEElement) IfAttr(condition bool, name, value string) *SVGCIRCLEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGCIRCLEElement) Text(text string) *SVGCIRCLEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGCIRCLEElement) TextF(format string, args ...any) *SVGCIRCLEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGCIRCLEElement) IfText(condition bool, text string) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGCIRCLEElement) IfTextF(condition bool, format string, args ...any) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGCIRCLEElement) Escaped(text string) *SVGCIRCLEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGCIRCLEElement) IfEscaped(condition bool, text string) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGCIRCLEElement) EscapedF(format string, args ...any) *SVGCIRCLEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGCIRCLEElement) IfEscapedF(condition bool, format string, args ...any) *SVGCIRCLEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGCIRCLEElement) CustomData(key, value string) *SVGCIRCLEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGCIRCLEElement) IfCustomData(condition bool, key, value string) *SVGCIRCLEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGCIRCLEElement) CustomDataF(key, format string, args ...any) *SVGCIRCLEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGCIRCLEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGCIRCLEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGCIRCLEElement) CustomDataRemove(key string) *SVGCIRCLEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x-axis coordinate of the center of the circle.
func (e *SVGCIRCLEElement) CX(f float64) *SVGCIRCLEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("cx", f)
	return e
}

// The x-axis coordinate of the center of the circle.
func (e *SVGCIRCLEElement) IfCX(condition bool, f float64) *SVGCIRCLEElement {
	if condition {
		e.CX(f)
	}
	return e
}

// The y-axis coordinate of the center of the circle.
func (e *SVGCIRCLEElement) CY(f float64) *SVGCIRCLEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("cy", f)
	return e
}

// The y-axis coordinate of the center of the circle.
func (e *SVGCIRCLEElement) IfCY(condition bool, f float64) *SVGCIRCLEElement {
	if condition {
		e.CY(f)
	}
	return e
}

// The radius of the circle.
func (e *SVGCIRCLEElement) R(f float64) *SVGCIRCLEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("r", f)
	return e
}

// The radius of the circle.
func (e *SVGCIRCLEElement) IfR(condition bool, f float64) *SVGCIRCLEElement {
	if condition {
		e.R(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGCIRCLEElement) ID(s string) *SVGCIRCLEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGCIRCLEElement) IDF(format string, args ...any) *SVGCIRCLEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGCIRCLEElement) IfID(condition bool, s string) *SVGCIRCLEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGCIRCLEElement) IfIDF(condition bool, format string, args ...any) *SVGCIRCLEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGCIRCLEElement) IDRemove(s string) *SVGCIRCLEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies a unique id for an element
func (e *SVGCIRCLEElement) IDRemoveF(format string, args ...any) *SVGCIRCLEElement {
	return e.IDRemove(fmt.Sprintf(format, args...))
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGCIRCLEElement) CLASS(s ...string) *SVGCIRCLEElement {
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(s...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGCIRCLEElement) IfCLASS(condition bool, s ...string) *SVGCIRCLEElement {
	if condition {
		e.CLASS(s...)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the attribute CLASS from the element.
func (e *SVGCIRCLEElement) CLASSRemove(s ...string) *SVGCIRCLEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCIRCLEElement) STYLEF(k string, format string, args ...any) *SVGCIRCLEElement {
	return e.STYLE(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGCIRCLEElement) IfSTYLE(condition bool, k string, v string) *SVGCIRCLEElement {
	if condition {
		e.STYLE(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCIRCLEElement) STYLE(k string, v string) *SVGCIRCLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	kv.Add(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGCIRCLEElement) IfSTYLEF(condition bool, k string, format string, args ...any) *SVGCIRCLEElement {
	if condition {
		e.STYLE(k, fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGCIRCLEElement) STYLEMap(m map[string]string) *SVGCIRCLEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for k, v := range m {
		kv.Add(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGCIRCLEElement) STYLERemove(keys ...string) *SVGCIRCLEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	for _, k := range keys {
		kv.Remove(k)
	}
	return e
}
