// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg feComposite is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feComposite> SVG filter primitive performs the combination of two input
// images pixel-wise in image space using one of the Porter-Duff compositing
// operations: over, in, atop, out, xor.
type SVGFECOMPOSITEElement struct {
	*Element
}

// Create a new SVGFECOMPOSITEElement element.
// This will create a new element with the tag
// "feComposite" during rendering.
func SVG_FECOMPOSITE(children ...ElementRenderer) *SVGFECOMPOSITEElement {
	e := NewElement("feComposite", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGFECOMPOSITEElement{Element: e}
}

func (e *SVGFECOMPOSITEElement) Children(children ...ElementRenderer) *SVGFECOMPOSITEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGFECOMPOSITEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGFECOMPOSITEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGFECOMPOSITEElement) BoolAttr(name string) *SVGFECOMPOSITEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGFECOMPOSITEElement) IfBoolAttr(condition bool, name string) *SVGFECOMPOSITEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFECOMPOSITEElement) Attr(name, value string) *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGFECOMPOSITEElement) IfAttr(condition bool, name, value string) *SVGFECOMPOSITEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFECOMPOSITEElement) Text(text string) *SVGFECOMPOSITEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGFECOMPOSITEElement) TextF(format string, args ...any) *SVGFECOMPOSITEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPOSITEElement) IfText(condition bool, text string) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGFECOMPOSITEElement) IfTextF(condition bool, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFECOMPOSITEElement) Escaped(text string) *SVGFECOMPOSITEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGFECOMPOSITEElement) IfEscaped(condition bool, text string) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGFECOMPOSITEElement) EscapedF(format string, args ...any) *SVGFECOMPOSITEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPOSITEElement) IfEscapedF(condition bool, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGFECOMPOSITEElement) CustomData(key, value string) *SVGFECOMPOSITEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGFECOMPOSITEElement) IfCustomData(condition bool, key, value string) *SVGFECOMPOSITEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGFECOMPOSITEElement) CustomDataF(key, format string, args ...any) *SVGFECOMPOSITEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGFECOMPOSITEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGFECOMPOSITEElement) CustomDataRemove(key string) *SVGFECOMPOSITEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// Input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IN(s string) *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in", s)
	return e
}

// Input for the compositing operation.
func (e *SVGFECOMPOSITEElement) INF(format string, args ...any) *SVGFECOMPOSITEElement {
	return e.IN(fmt.Sprintf(format, args...))
}

// Input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IfIN(condition bool, s string) *SVGFECOMPOSITEElement {
	if condition {
		e.IN(s)
	}
	return e
}

// Input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IfINF(condition bool, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.IN(fmt.Sprintf(format, args...))
	}
	return e
}

// Input for the compositing operation.
//
// Remove the attribute IN from the element.
func (e *SVGFECOMPOSITEElement) INRemove() *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in")
	return e
}

// Second input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IN_2(s string) *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("in2", s)
	return e
}

// Second input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IN_2F(format string, args ...any) *SVGFECOMPOSITEElement {
	return e.IN_2(fmt.Sprintf(format, args...))
}

// Second input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IfIN_2(condition bool, s string) *SVGFECOMPOSITEElement {
	if condition {
		e.IN_2(s)
	}
	return e
}

// Second input for the compositing operation.
func (e *SVGFECOMPOSITEElement) IfIN_2F(condition bool, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.IN_2(fmt.Sprintf(format, args...))
	}
	return e
}

// Second input for the compositing operation.
//
// Remove the attribute IN_2 from the element.
func (e *SVGFECOMPOSITEElement) IN_2Remove() *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("in2")
	return e
}

// The type of compositing operation.
func (e *SVGFECOMPOSITEElement) OPERATOR(c SVGFeCompositeOperatorChoice) *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("operator", string(c))
	return e
}

type SVGFeCompositeOperatorChoice string

const (
	// The source image is composited over the destination image.
	SVGFeCompositeOperator_over SVGFeCompositeOperatorChoice = "over"
	// The part of the source image that lies inside of the destination image is
	// composited over the destination image.
	SVGFeCompositeOperator_in SVGFeCompositeOperatorChoice = "in"
	// The part of the source image that lies outside of the destination image is
	// composited over the destination image.
	SVGFeCompositeOperator_out SVGFeCompositeOperatorChoice = "out"
	// The part of the source image that lies inside of the destination image is
	// composited over the destination image and replaces the destination image.
	SVGFeCompositeOperator_atop SVGFeCompositeOperatorChoice = "atop"
	// The part of the source image that lies outside of the destination image is
	// composited over the destination image.
	SVGFeCompositeOperator_xor SVGFeCompositeOperatorChoice = "xor"
	// A standard arithmetic operator is applied (
	SVGFeCompositeOperator_arithmetic SVGFeCompositeOperatorChoice = "arithmetic"
)

// The type of compositing operation.
// Remove the attribute OPERATOR from the element.
func (e *SVGFECOMPOSITEElement) OPERATORRemove() *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("operator")
	return e
}

// First value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) K_1(f float64) *SVGFECOMPOSITEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("k1", f)
	return e
}

// First value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) IfK_1(condition bool, f float64) *SVGFECOMPOSITEElement {
	if condition {
		e.K_1(f)
	}
	return e
}

// Second value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) K_2(f float64) *SVGFECOMPOSITEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("k2", f)
	return e
}

// Second value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) IfK_2(condition bool, f float64) *SVGFECOMPOSITEElement {
	if condition {
		e.K_2(f)
	}
	return e
}

// Third value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) K_3(f float64) *SVGFECOMPOSITEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("k3", f)
	return e
}

// Third value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) IfK_3(condition bool, f float64) *SVGFECOMPOSITEElement {
	if condition {
		e.K_3(f)
	}
	return e
}

// Fourth value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) K_4(f float64) *SVGFECOMPOSITEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("k4", f)
	return e
}

// Fourth value to use in the arithmetic operation.
func (e *SVGFECOMPOSITEElement) IfK_4(condition bool, f float64) *SVGFECOMPOSITEElement {
	if condition {
		e.K_4(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPOSITEElement) ID(s string) *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPOSITEElement) IDF(format string, args ...any) *SVGFECOMPOSITEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFECOMPOSITEElement) IfID(condition bool, s string) *SVGFECOMPOSITEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFECOMPOSITEElement) IfIDF(condition bool, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGFECOMPOSITEElement) IDRemove() *SVGFECOMPOSITEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOMPOSITEElement) CLASS(s string) *SVGFECOMPOSITEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFECOMPOSITEElement) IfCLASS(condition bool, s string) *SVGFECOMPOSITEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGFECOMPOSITEElement) CLASSRemove(s ...string) *SVGFECOMPOSITEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) STYLEPairs(pairs ...string) *SVGFECOMPOSITEElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) STYLE(s string) *SVGFECOMPOSITEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) IfSTYLE(condition bool, s string) *SVGFECOMPOSITEElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) STYLEAdd(k string, v string) *SVGFECOMPOSITEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) STYLEAddF(k string, format string, args ...any) *SVGFECOMPOSITEElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) IfSTYLEAdd(condition bool, k string, v string) *SVGFECOMPOSITEElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFECOMPOSITEElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGFECOMPOSITEElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGFECOMPOSITEElement) STYLEMap(m map[string]string) *SVGFECOMPOSITEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGFECOMPOSITEElement) STYLERemove(keys ...string) *SVGFECOMPOSITEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
