// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg set is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <set> SVG element provides a simple means of just setting the value of an
// attribute for a specified duration. It supports all attribute types,
// including those that cannot reasonably be interpolated, such as string and
// boolean values. The <set> element is non-additive. The additive and
// accumulate attributes are not allowed, and will be ignored if specified.
type SVGSETElement struct {
	*Element
}

// Create a new SVGSETElement element.
// This will create a new element with the tag
// "set" during rendering.
func SVG_SET(children ...ElementRenderer) *SVGSETElement {
	e := NewElement("set", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGSETElement{Element: e}
}

func (e *SVGSETElement) Children(children ...ElementRenderer) *SVGSETElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGSETElement) IfChildren(condition bool, children ...ElementRenderer) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGSETElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGSETElement) BoolAttr(name string) *SVGSETElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGSETElement) IfBoolAttr(condition bool, name string) *SVGSETElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGSETElement) Attr(name, value string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGSETElement) IfAttr(condition bool, name, value string) *SVGSETElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGSETElement) Text(text string) *SVGSETElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGSETElement) TextF(format string, args ...any) *SVGSETElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGSETElement) IfText(condition bool, text string) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGSETElement) IfTextF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGSETElement) Escaped(text string) *SVGSETElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGSETElement) IfEscaped(condition bool, text string) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGSETElement) EscapedF(format string, args ...any) *SVGSETElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGSETElement) IfEscapedF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGSETElement) CustomData(key, value string) *SVGSETElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGSETElement) IfCustomData(condition bool, key, value string) *SVGSETElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGSETElement) CustomDataF(key, format string, args ...any) *SVGSETElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGSETElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGSETElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGSETElement) CustomDataRemove(key string) *SVGSETElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The target attribute value to assign on end.
func (e *SVGSETElement) TO(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("to", s)
	return e
}

// The target attribute value to assign on end.
func (e *SVGSETElement) TOF(format string, args ...any) *SVGSETElement {
	return e.TO(fmt.Sprintf(format, args...))
}

// The target attribute value to assign on end.
func (e *SVGSETElement) IfTO(condition bool, s string) *SVGSETElement {
	if condition {
		e.TO(s)
	}
	return e
}

// The target attribute value to assign on end.
func (e *SVGSETElement) IfTOF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.TO(fmt.Sprintf(format, args...))
	}
	return e
}

// The target attribute value to assign on end.
//
// Remove the attribute TO from the element.
func (e *SVGSETElement) TORemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("to")
	return e
}

// The name of the attribute to assign.
func (e *SVGSETElement) ATTRIBUTE_NAME(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("attributeName", s)
	return e
}

// The name of the attribute to assign.
func (e *SVGSETElement) ATTRIBUTE_NAMEF(format string, args ...any) *SVGSETElement {
	return e.ATTRIBUTE_NAME(fmt.Sprintf(format, args...))
}

// The name of the attribute to assign.
func (e *SVGSETElement) IfATTRIBUTE_NAME(condition bool, s string) *SVGSETElement {
	if condition {
		e.ATTRIBUTE_NAME(s)
	}
	return e
}

// The name of the attribute to assign.
func (e *SVGSETElement) IfATTRIBUTE_NAMEF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.ATTRIBUTE_NAME(fmt.Sprintf(format, args...))
	}
	return e
}

// The name of the attribute to assign.
//
// Remove the attribute ATTRIBUTE_NAME from the element.
func (e *SVGSETElement) ATTRIBUTE_NAMERemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("attributeName")
	return e
}

// The namespace in which the target attribute and its associated values are
// defined.
func (e *SVGSETElement) ATTRIBUTE_TYPE(c SVGSetAttributeTypeChoice) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("attributeType", string(c))
	return e
}

type SVGSetAttributeTypeChoice string

const (
	// The namespace in which the target attribute and its associated values are
	// defined.
	SVGSetAttributeType_auto SVGSetAttributeTypeChoice = "auto"
	// The namespace in which the target attribute and its associated values are
	// defined.
	SVGSetAttributeType_CSS SVGSetAttributeTypeChoice = "CSS"
	// The namespace in which the target attribute and its associated values are
	// defined.
	SVGSetAttributeType_XML SVGSetAttributeTypeChoice = "XML"
	// The namespace in which the target attribute and its associated values are
	// defined.
	SVGSetAttributeType_XMLNS SVGSetAttributeTypeChoice = "XMLNS"
	// The namespace in which the target attribute and its associated values are
	// defined.
	SVGSetAttributeType_empty SVGSetAttributeTypeChoice = "empty"
)

// The namespace in which the target attribute and its associated values are
// defined.
// Remove the attribute ATTRIBUTE_TYPE from the element.
func (e *SVGSETElement) ATTRIBUTE_TYPERemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("attributeType")
	return e
}

// The begin time for the element.
func (e *SVGSETElement) BEGIN(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("begin", s)
	return e
}

// The begin time for the element.
func (e *SVGSETElement) BEGINF(format string, args ...any) *SVGSETElement {
	return e.BEGIN(fmt.Sprintf(format, args...))
}

// The begin time for the element.
func (e *SVGSETElement) IfBEGIN(condition bool, s string) *SVGSETElement {
	if condition {
		e.BEGIN(s)
	}
	return e
}

// The begin time for the element.
func (e *SVGSETElement) IfBEGINF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.BEGIN(fmt.Sprintf(format, args...))
	}
	return e
}

// The begin time for the element.
//
// Remove the attribute BEGIN from the element.
func (e *SVGSETElement) BEGINRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("begin")
	return e
}

// The simple duration for the element.
func (e *SVGSETElement) DUR(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dur", s)
	return e
}

// The simple duration for the element.
func (e *SVGSETElement) DURF(format string, args ...any) *SVGSETElement {
	return e.DUR(fmt.Sprintf(format, args...))
}

// The simple duration for the element.
func (e *SVGSETElement) IfDUR(condition bool, s string) *SVGSETElement {
	if condition {
		e.DUR(s)
	}
	return e
}

// The simple duration for the element.
func (e *SVGSETElement) IfDURF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.DUR(fmt.Sprintf(format, args...))
	}
	return e
}

// The simple duration for the element.
//
// Remove the attribute DUR from the element.
func (e *SVGSETElement) DURRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dur")
	return e
}

// The end for the element.
func (e *SVGSETElement) END(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("end", s)
	return e
}

// The end for the element.
func (e *SVGSETElement) ENDF(format string, args ...any) *SVGSETElement {
	return e.END(fmt.Sprintf(format, args...))
}

// The end for the element.
func (e *SVGSETElement) IfEND(condition bool, s string) *SVGSETElement {
	if condition {
		e.END(s)
	}
	return e
}

// The end for the element.
func (e *SVGSETElement) IfENDF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.END(fmt.Sprintf(format, args...))
	}
	return e
}

// The end for the element.
//
// Remove the attribute END from the element.
func (e *SVGSETElement) ENDRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("end")
	return e
}

// The minimum value allowed for the attribute.
func (e *SVGSETElement) MIN(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("min", s)
	return e
}

// The minimum value allowed for the attribute.
func (e *SVGSETElement) MINF(format string, args ...any) *SVGSETElement {
	return e.MIN(fmt.Sprintf(format, args...))
}

// The minimum value allowed for the attribute.
func (e *SVGSETElement) IfMIN(condition bool, s string) *SVGSETElement {
	if condition {
		e.MIN(s)
	}
	return e
}

// The minimum value allowed for the attribute.
func (e *SVGSETElement) IfMINF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.MIN(fmt.Sprintf(format, args...))
	}
	return e
}

// The minimum value allowed for the attribute.
//
// Remove the attribute MIN from the element.
func (e *SVGSETElement) MINRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("min")
	return e
}

// The maximum value allowed for the attribute.
func (e *SVGSETElement) MAX(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("max", s)
	return e
}

// The maximum value allowed for the attribute.
func (e *SVGSETElement) MAXF(format string, args ...any) *SVGSETElement {
	return e.MAX(fmt.Sprintf(format, args...))
}

// The maximum value allowed for the attribute.
func (e *SVGSETElement) IfMAX(condition bool, s string) *SVGSETElement {
	if condition {
		e.MAX(s)
	}
	return e
}

// The maximum value allowed for the attribute.
func (e *SVGSETElement) IfMAXF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.MAX(fmt.Sprintf(format, args...))
	}
	return e
}

// The maximum value allowed for the attribute.
//
// Remove the attribute MAX from the element.
func (e *SVGSETElement) MAXRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("max")
	return e
}

// Defines how the element is restarted.
func (e *SVGSETElement) RESTART(c SVGSetRestartChoice) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("restart", string(c))
	return e
}

type SVGSetRestartChoice string

const (
	// Defines how the element is restarted.
	SVGSetRestart_always SVGSetRestartChoice = "always"
	// Defines how the element is restarted.
	SVGSetRestart_whenNotActive SVGSetRestartChoice = "whenNotActive"
	// Defines how the element is restarted.
	SVGSetRestart_never SVGSetRestartChoice = "never"
)

// Defines how the element is restarted.
// Remove the attribute RESTART from the element.
func (e *SVGSETElement) RESTARTRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("restart")
	return e
}

// Defines the number of times the element is repeated.
func (e *SVGSETElement) REPEAT_COUNT(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("repeatCount", s)
	return e
}

// Defines the number of times the element is repeated.
func (e *SVGSETElement) REPEAT_COUNTF(format string, args ...any) *SVGSETElement {
	return e.REPEAT_COUNT(fmt.Sprintf(format, args...))
}

// Defines the number of times the element is repeated.
func (e *SVGSETElement) IfREPEAT_COUNT(condition bool, s string) *SVGSETElement {
	if condition {
		e.REPEAT_COUNT(s)
	}
	return e
}

// Defines the number of times the element is repeated.
func (e *SVGSETElement) IfREPEAT_COUNTF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.REPEAT_COUNT(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the number of times the element is repeated.
//
// Remove the attribute REPEAT_COUNT from the element.
func (e *SVGSETElement) REPEAT_COUNTRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("repeatCount")
	return e
}

// Defines the duration for the element to repeat.
func (e *SVGSETElement) REPEAT_DUR(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("repeatDur", s)
	return e
}

// Defines the duration for the element to repeat.
func (e *SVGSETElement) REPEAT_DURF(format string, args ...any) *SVGSETElement {
	return e.REPEAT_DUR(fmt.Sprintf(format, args...))
}

// Defines the duration for the element to repeat.
func (e *SVGSETElement) IfREPEAT_DUR(condition bool, s string) *SVGSETElement {
	if condition {
		e.REPEAT_DUR(s)
	}
	return e
}

// Defines the duration for the element to repeat.
func (e *SVGSETElement) IfREPEAT_DURF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.REPEAT_DUR(fmt.Sprintf(format, args...))
	}
	return e
}

// Defines the duration for the element to repeat.
//
// Remove the attribute REPEAT_DUR from the element.
func (e *SVGSETElement) REPEAT_DURRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("repeatDur")
	return e
}

// Defines the value the animation will have before the begin event.
func (e *SVGSETElement) FILL(c SVGSetFillChoice) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("fill", string(c))
	return e
}

type SVGSetFillChoice string

const (
	// Defines the value the animation will have before the begin event.
	SVGSetFill_remove SVGSetFillChoice = "remove"
	// Defines the value the animation will have before the begin event.
	SVGSetFill_freeze SVGSetFillChoice = "freeze"
)

// Defines the value the animation will have before the begin event.
// Remove the attribute FILL from the element.
func (e *SVGSETElement) FILLRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("fill")
	return e
}

// Specifies a unique id for an element
func (e *SVGSETElement) ID(s string) *SVGSETElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGSETElement) IDF(format string, args ...any) *SVGSETElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGSETElement) IfID(condition bool, s string) *SVGSETElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGSETElement) IfIDF(condition bool, format string, args ...any) *SVGSETElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGSETElement) IDRemove() *SVGSETElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGSETElement) CLASS(s string) *SVGSETElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGSETElement) IfCLASS(condition bool, s string) *SVGSETElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGSETElement) CLASSRemove(s ...string) *SVGSETElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) STYLEPairs(pairs ...string) *SVGSETElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) STYLE(s string) *SVGSETElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) IfSTYLE(condition bool, s string) *SVGSETElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) STYLEAdd(k string, v string) *SVGSETElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) STYLEAddF(k string, format string, args ...any) *SVGSETElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) IfSTYLEAdd(condition bool, k string, v string) *SVGSETElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGSETElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGSETElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGSETElement) STYLEMap(m map[string]string) *SVGSETElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGSETElement) STYLERemove(keys ...string) *SVGSETElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
