// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.tmpl
// Generated: 2025-11-04T02:22:53+01:00

// package svg line is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <line> SVG element is an SVG basic shape, used to create a line
// connecting two points.
type SVGLINEElement struct {
	*Element
}

// Create a new SVGLINEElement element.
// This will create a new element with the tag
// "line" during rendering.
func SVG_LINE(children ...ElementRenderer) *SVGLINEElement {
	e := NewElement("line", children...)
	e.IsSelfClosing = false
	e.Descendants = children

	return &SVGLINEElement{Element: e}
}

func (e *SVGLINEElement) Children(children ...ElementRenderer) *SVGLINEElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGLINEElement) IfChildren(condition bool, children ...ElementRenderer) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGLINEElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGLINEElement) BoolAttr(name string) *SVGLINEElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGLINEElement) IfBoolAttr(condition bool, name string) *SVGLINEElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGLINEElement) Attr(name, value string) *SVGLINEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGLINEElement) IfAttr(condition bool, name, value string) *SVGLINEElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGLINEElement) Text(text string) *SVGLINEElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGLINEElement) TextF(format string, args ...any) *SVGLINEElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGLINEElement) IfText(condition bool, text string) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGLINEElement) IfTextF(condition bool, format string, args ...any) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGLINEElement) Escaped(text string) *SVGLINEElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGLINEElement) IfEscaped(condition bool, text string) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGLINEElement) EscapedF(format string, args ...any) *SVGLINEElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGLINEElement) IfEscapedF(condition bool, format string, args ...any) *SVGLINEElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

func (e *SVGLINEElement) CustomData(key, value string) *SVGLINEElement {
	if e.CustomDataAttributes == nil {
		e.CustomDataAttributes = treemap.New[string, string]()
	}
	e.CustomDataAttributes.Set(key, value)
	return e
}

func (e *SVGLINEElement) IfCustomData(condition bool, key, value string) *SVGLINEElement {
	if condition {
		e.CustomData(key, value)
	}
	return e
}

func (e *SVGLINEElement) CustomDataF(key, format string, args ...any) *SVGLINEElement {
	return e.CustomData(key, fmt.Sprintf(format, args...))
}

func (e *SVGLINEElement) IfCustomDataF(condition bool, key, format string, args ...any) *SVGLINEElement {
	if condition {
		e.CustomData(key, fmt.Sprintf(format, args...))
	}
	return e
}

func (e *SVGLINEElement) CustomDataRemove(key string) *SVGLINEElement {
	if e.CustomDataAttributes == nil {
		return e
	}
	e.CustomDataAttributes.Del(key)
	return e
}

// The x-axis coordinate of the starting point of the line.
func (e *SVGLINEElement) X_1(f float64) *SVGLINEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x1", f)
	return e
}

// The x-axis coordinate of the starting point of the line.
func (e *SVGLINEElement) IfX_1(condition bool, f float64) *SVGLINEElement {
	if condition {
		e.X_1(f)
	}
	return e
}

// The y-axis coordinate of the starting point of the line.
func (e *SVGLINEElement) Y_1(f float64) *SVGLINEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y1", f)
	return e
}

// The y-axis coordinate of the starting point of the line.
func (e *SVGLINEElement) IfY_1(condition bool, f float64) *SVGLINEElement {
	if condition {
		e.Y_1(f)
	}
	return e
}

// The x-axis coordinate of the ending point of the line.
func (e *SVGLINEElement) X_2(f float64) *SVGLINEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("x2", f)
	return e
}

// The x-axis coordinate of the ending point of the line.
func (e *SVGLINEElement) IfX_2(condition bool, f float64) *SVGLINEElement {
	if condition {
		e.X_2(f)
	}
	return e
}

// The y-axis coordinate of the ending point of the line.
func (e *SVGLINEElement) Y_2(f float64) *SVGLINEElement {
	if e.FloatAttributes == nil {
		e.FloatAttributes = treemap.New[string, float64]()
	}
	e.FloatAttributes.Set("y2", f)
	return e
}

// The y-axis coordinate of the ending point of the line.
func (e *SVGLINEElement) IfY_2(condition bool, f float64) *SVGLINEElement {
	if condition {
		e.Y_2(f)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGLINEElement) ID(s string) *SVGLINEElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGLINEElement) IDF(format string, args ...any) *SVGLINEElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGLINEElement) IfID(condition bool, s string) *SVGLINEElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGLINEElement) IfIDF(condition bool, format string, args ...any) *SVGLINEElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
//
// Remove the attribute ID from the element.
func (e *SVGLINEElement) IDRemove() *SVGLINEElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGLINEElement) CLASS(s string) *SVGLINEElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGLINEElement) IfCLASS(condition bool, s string) *SVGLINEElement {
	if condition {
		e.CLASS(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
//
// Remove the values from the attribute CLASS in the element.
func (e *SVGLINEElement) CLASSRemove(s ...string) *SVGLINEElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) STYLEPairs(pairs ...string) *SVGLINEElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("STYLEPairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) STYLE(s string) *SVGLINEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.STYLEPairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) IfSTYLE(condition bool, s string) *SVGLINEElement {
	if condition {
		e.STYLE(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) STYLEAdd(k string, v string) *SVGLINEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.STYLEPairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) STYLEAddF(k string, format string, args ...any) *SVGLINEElement {
	return e.STYLEAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) IfSTYLEAdd(condition bool, k string, v string) *SVGLINEElement {
	if condition {
		e.STYLEAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGLINEElement) IfSTYLEAddF(condition bool, k string, format string, args ...any) *SVGLINEElement {
	if condition {
		e.STYLEAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
//
// Add the attributes in the map to the element.
func (e *SVGLINEElement) STYLEMap(m map[string]string) *SVGLINEElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.STYLEPairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute STYLE from the element.
func (e *SVGLINEElement) STYLERemove(keys ...string) *SVGLINEElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
